### ISSUE TITLE
[ws] benching test is flaky

### ISSUE THREAD

**Issue by grian32** [denoland/deno_std#1183]
failed on #1179 twice, once originally and again after an empty commit.

ran fine on #1181

**Comment by cmorten** [comment]
Seen as well on #1128. REF: https://github.com/denoland/deno_std/runs/3459810632

```console
...

running 11 tests from file:///Users/runner/work/deno_std/deno_std/testing/bench_test.ts
test benching ...running 5 benchmarks ...
benchmark forIncrementX1e3 ... 
    0.08709699999999998ms
benchmark forDecrementX1e3 ... 
    0.028298999999996965ms
benchmark forAwaitFetchDenolandX10 ... 
    878.8115389999999ms
benchmark promiseAllFetchDenolandX10 ... 
TypeError: error sending request for url (https://deno.land/): connection closed before message completed
benchmark result: FAIL. 3 measured; 1 filtered
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at async mainFetch (deno:ext/fetch/26_fetch.js:265:14)
 FAILED (1008ms)

...

error: Test failed
failures:

benching
TypeError: error sending request for url (https://deno.land/): connection closed before message completed
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at async mainFetch (deno:ext/fetch/26_fetch.js:265:14)

failures:

	benching

test result: FAILED. 2727 passed; 1 failed; 12 ignored; 0 measured; 0 filtered out (391
```

**Comment by bartlomieju** [comment]
No longer an issue.
