### ISSUE TITLE
Deno Node API throwing assertion error about wrong Node Version though installed

### ISSUE THREAD

**Issue by Noxdor** [denoland/deno_std#1402]
**Describe the bug**

When I'm trying to import a module using the Deno Node API, I get an assertion error, that the current nodejs version is not sufficient. Though it should be. Running `which node` I get `.../.nvm/versions/node/v14.17.6/bin/node` which is higher than the required 8.0.0. It tells me though, that the current nodejs version is 1.14.0. Where does this check happen? 

**Steps to Reproduce**
1. Try to use the `node-opcua` module in a simple deno file.

```ts
import { createRequire } from "https://deno.land/std@0.111.0/node/module.ts"

const require = createRequire(import.meta.url)
const { OPCUAServer } = require("node-opcua")

console.log(OPCUAServer)
```
2. Run the code.

```bash
deno run --unstable --allow-read --allow-env opc.ts
```

3. Get the error message.

```bash
warning node-opcua: Required nodejs version >=8.0.0 not satisfied with current nodejs version v1.14.0.
error: Uncaught AssertionError
    Error.captureStackTrace(this, stackStartFn || stackStartFunction);
          ^
    at new AssertionError (https://deno.land/std@0.111.0/node/assertion_error.ts:529:11)
    at toNode (https://deno.land/std@0.111.0/node/assert.ts:58:15)
    at assert (https://deno.land/std@0.111.0/node/assert.ts:76:3)
    at Object.<anonymous> (file:///home/lennart/programming/hermos/backend/node_modules/node-opcua-crypto/dist/source/crypto_utils.js:157:1)
    at Module._compile (https://deno.land/std@0.111.0/node/module.ts:153:36)
    at Object.Module._extensions..js (https://deno.land/std@0.111.0/node/module.ts:1094:10)
    at Module.load (https://deno.land/std@0.111.0/node/module.ts:132:34)
    at Function._load (https://deno.land/std@0.111.0/node/module.ts:398:14)
    at Module.require (https://deno.land/std@0.111.0/node/module.ts:118:21)
    at require (https://deno.land/std@0.111.0/node/module.ts:1149:16)
```

**Expected behavior**

Logging the imported object successfully.

**Environment**

- OS: `4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux` (WSL 2)
- deno version:
```
deno 1.14.0 (release, x86_64-unknown-linux-gnu)
v8 9.4.146.15
typescript 4.4.2
```
- std version: 0.111.0

**Comment by Noxdor** [comment]
So it seems the assertion error comes from the node package (node-opcua). It checks for a correct node version and instead reads the deno version as node version (see my original post above and compare the error message and my installed deno version).
Anyone having an idea how to trick the module into believing me the correct node version is installed?
