### ISSUE TITLE
std/node assert.throws is broken

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_std#1459]
Given this code:
```js
assert.throws(() => {
  readline.clearScreenDown(writable, null);
}, /ERR_INVALID_CALLBACK/);
```
Which throws instance of `ERR_INVALID_CALLBACK` I get following failure:
```
Uncaught TypeError: Cannot destructure property 'cb' of 'object null' as it is null.
error: Uncaught AssertionError: The input did not match the regular expression /ERR_INVALID_CALLBACK/. Input:

'TypeError: Callback must be a function. Received null'

    Error.captureStackTrace(this, stackStartFn || stackStartFunction);
          ^
    at new AssertionError (file:///Users/biwanczuk/dev/deno_std/node/assertion_error.ts:529:11)
    at createAssertionError (file:///Users/biwanczuk/dev/deno_std/node/assert.ts:26:17)
    at validateThrownError (file:///Users/biwanczuk/dev/deno_std/node/assert.ts:756:11)
    at Function.throws (file:///Users/biwanczuk/dev/deno_std/node/assert.ts:136:7)
    at Object.<anonymous> (file:///Users/biwanczuk/dev/deno_std/node/_tools/suites/parallel/test-readline-csi.js:44:8)
    at Module._compile (file:///Users/biwanczuk/dev/deno_std/node/module.ts:251:36)
```

Quick check shows that `assert.throws` is significantly different than its implementation in Node codebase, we should change the implementation to match Node's

**Comment by bartlomieju** [comment]
Fixed by @kt3k in #1470
