### ISSUE TITLE
"serveDirectory TLS" test is flaky

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_std#1462]
```
serveDirectory TLS
ConnectionRefused: Connection refused (os error 61)
    at async Object.connectTls (deno:ext/net/02_tls.js:35:17)
    at async file:///Users/runner/work/deno_std/deno_std/http/file_server_test.ts:414:18
    at async testStepSanitizer (deno:runtime/js/40_testing.js:161:7)
    at async asyncOpSanitizer (deno:runtime/js/40_testing.js:42:9)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:112:7)
    at async Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:144:9)
    at async runTest (deno:runtime/js/40_testing.js:349:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:460:22)

failures:

	serveDirectory TLS
```

https://github.com/denoland/deno_std/runs/3994671742?check_suite_focus=true

**Comment by bartlomieju** [comment]
Seems to no longer be the case. Closing
