### ISSUE TITLE
_tools/lint.js doesn't fail on CI

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_std#1575]
I'm getting the following lint errors as of this change:
```
$ deno run -A _tools/lint.js 
(ban-types) This provides no type safety because it represents all functions and classes
  listeners(eventName: string | symbol): Function[];
                                         ^^^^^^^^
    at /home/bnoordhuis/src/std/node/_events.d.ts:429:41

    hint: Define the function shape explicitly
    help: for further information visit https://lint.deno.land/#ban-types

(ban-types) This provides no type safety because it represents all functions and classes
  rawListeners(eventName: string | symbol): Function[];
                                            ^^^^^^^^
    at /home/bnoordhuis/src/std/node/_events.d.ts:459:44

    hint: Define the function shape explicitly
    help: for further information visit https://lint.deno.land/#ban-types

Found 2 problems
Checked 648 files
```

_Originally posted by @bnoordhuis in https://github.com/denoland/deno_std/issues/1570#issuecomment-968769382_

**Comment by bartlomieju** [comment]
I'm getting this errors locally too and it shows up on CI as well: https://github.com/denoland/deno_std/runs/4205386249?check_suite_focus=true

However the CI did not fail. CC @kt3k can you take a look?
