### ISSUE TITLE
Node compat test runner doesn't fail when it should

### ISSUE THREAD

**Issue by bnoordhuis** [denoland/deno_std#1577]
At commit 23c868be, I see test failures but the runner thinks everything's okay:
```
$ deno test --allow-read --allow-run node/_tools/test.ts
# <...>
271 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```
Output (includes control codes): [test.txt](https://github.com/denoland/deno_std/files/7538570/test.txt)

**Comment by bartlomieju** [comment]
Example of failing test:
```
deno run -A --unstable -r --no-check node/_tools/require.ts /Users/biwanczuk/dev/deno_std/node/_tools/suites/parallel/test-stream2-pipe-error-handling.js
Uncaught RangeError: The argument 'size' is invalid. Received NaN
```

Adding some logs to `resume_` function in `node/_stream/readable_internal.ts`:
```
deno run -A --unstable -r --no-check node/_tools/require.ts /Users/biwanczuk/dev/deno_std/node/_tools/suites/parallel/test-stream2-pipe-error-handling.js
error thrown in resume_ RangeError [ERR_INVALID_ARG_VALUE]ment 'size' is invalid. Received NaN
    at assertSize (file:///Users/biwanczuk/dev/deno_std/node/_buffer.js:216:11)
    at allocUnsafe (file:///Users/biwanczuk/dev/deno_std/node/_buffer.js:235:3)
    at Function.Buffer.allocUnsafe (file:///Users/biwanczuk/dev/deno_std/node/_buffer.js:240:10)
    at Readable.source._read (file:///Users/biwanczuk/dev/deno_std/node/_tools/suites/parallel/test-stream2-pipe-error-handling.js:43:24)
    at Readable.read (file:///Users/biwanczuk/dev/deno_std/node/_stream/readable.ts:202:14)
    at resume_ (file:///Users/biwanczuk/dev/deno_std/node/_stream/readable_internal.ts:432:14)
    at file:///Users/biwanczuk/dev/deno_std/node/_stream/readable_internal.ts:424:26
Uncaught RangeError: The argument 'size' is invalid. Received NaN
```
Proper error is thrown but never surfaced - `resume_` should be called scheduled by `process.nextTick`, but right now it uses `queueMicrotask` and errors being swalled seems to be directly connected to https://github.com/denoland/deno/issues/4350
