### ISSUE TITLE
node: `node/open` should throw error if we don't add `allow-read` flag

### ISSUE THREAD

**Issue by getspooky** [denoland/deno_std#1596]
**Describe the bug**

`open` function should throw error if we don't add `allow-read` flag

```ts
import { open, closeSync } from "./node/fs.ts";

const file = Deno.makeTempFileSync();
let fd1: number;
await new Promise<number>((resolve, reject) => {
  open(file, (err, fd) => {
    if (err) reject(err);
    resolve(fd);
  });
})
  .then(fd => {
    fd1 = fd;
  })
  .finally(() => closeSync(fd1));
```

**Steps to Reproduce**

- Run 
```sh
deno run --unstable --allow-write  test.ts
```

- Result 
```sh
error: Uncaught (in promise) TypeError: missing or invalid `rid`
  Deno.close(fd);
       ^
    at opSync (deno:core/01_core.js:142:12)
    at Object.close (deno:core/01_core.js:162:5)
```

**Expected behavior**

```sh
error: Uncaught PermissionDenied: Requires read access to "/tmp/a21722de", run again with the --allow-read flag
  return Deno.openSync(path, convertFlagAndModeToOptions(flags, mode)).rid;
```

**Environment**

- OS: e.g. Ubuntu 20.04
- deno version: 1.16.1

**Comment by kt3k** [comment]
Your example seems having error in `finally` handler. If you change the example like the below, you should see read permission error:
```ts
import { open, closeSync } from "./node/fs.ts";

const file = Deno.makeTempFileSync();
let fd1: number;
await new Promise<number>((resolve, reject) => {
  open(file, (err, fd) => {
    if (err) reject(err);
    resolve(fd);
  });
})
  .then(fd => {
    fd1 = fd;
  })
  .finally(() => {
    if (fd1) {
      closeSync(fd1);
    }
  });
```
