### ISSUE TITLE
node: Errors in http server

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_std#1620]
Running benchmarks I hit following errors:
```
/Users/biwanczuk/dev/deno_node_benchmarks/benchmark/http/simple.js type=bytes len=4 chunks=1 c=500 chunkedEnc=1 duration=5 20903.21
error: Uncaught (in promise) Http: connection closed before message completed
    at async Object.respondWith (deno:ext/http/01_http.js:202:11)
^[[A/Users/biwanczuk/dev/deno_node_benchmarks/benchmark/http/simple.js type=bytes len=4 chunks=1 c=500 chunkedEnc=0 duration=5 21239.47
error: Uncaught (in promise) Http: connection closed before message completed
    at async Object.respondWith (deno:ext/http/01_http.js:202:11)
```
and
```
/Users/biwanczuk/dev/deno_node_benchmarks/benchmark/http/simple.js type=bytes len=4 chunks=4 c=50 chunkedEnc=0 duration=5 10772.35
error: Uncaught (in promise) Http: error writing a body to connection: Broken pipe (os error 32)
        for await (const reqEvent of httpConn) {
                         ^
    at async HttpConn.nextRequest (deno:ext/http/01_http.js:67:23)
    at async Object.next (deno:ext/http/01_http.js:137:26)
    at async go (file:///Users/biwanczuk/dev/deno_std/node/http.ts:267:26)
error: Uncaught (in promise) Http: error writing a body to connection: Broken pipe (os error 32)
        for await (const reqEvent of httpConn) {
                         ^
    at async HttpConn.nextRequest (deno:ext/http/01_http.js:67:23)
    at async Object.next (deno:ext/http/01_http.js:137:26)
    at async go (file:///Users/biwanczuk/dev/deno_std/node/http.ts:267:26)
```

**Comment by bnoordhuis** [comment]
The second one is a bug in std, the first one I'm not sure of. I can't seem to suppress it in std/node/http.ts.

**Comment by bnoordhuis** [comment]
> [..] the first one I'm not sure of. I can't seem to suppress it in std/node/http.ts.

As (belated) follow-up: I suspect it's another incarnation of #833. I'll investigate.
