### ISSUE TITLE
node: Error when requiring package doesn't return 1 exit code

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_std#1627]
```
❯ deno run --no-check --compat --unstable --allow-read --allow-write=./ ./bin/eslint.js lib/ tests/
Not implemented: process.on("uncaughtException")
Not implemented: process.on("unhandledRejection")

Oops! Something went wrong! :(

ESLint: 8.2.0

PermissionDenied: Requires env access to "IGNORE_TEST_WIN32", run again with the --allow-env flag
    at Object.opSync (deno:core/01_core.js:142:12)
    at Object.getEnv [as get] (deno:runtime/js/30_os.js:56:17)
    at Object.get (https://deno.land/std@0.115.0/node/process.ts:63:21)
    at Object.<anonymous> (file:///Users/biwanczuk/dev/eslint/node_modules/ignore/index.js:445:32)
    at Module._compile (https://deno.land/std@0.115.0/node/module.ts:251:36)
    at Object.Module._extensions..js (https://deno.land/std@0.115.0/node/module.ts:1276:10)
    at Module.load (https://deno.land/std@0.115.0/node/module.ts:230:33)
    at Function._load (https://deno.land/std@0.115.0/node/module.ts:539:14)
    at Module.require (https://deno.land/std@0.115.0/node/module.ts:216:21)
    at require (https://deno.land/std@0.115.0/node/module.ts:1331:16)

❯ echo $status
0

```

This is a blocker for https://github.com/eslint/eslint/pull/15336

**Comment by bartlomieju** [comment]
Probably related to this bit:
https://github.com/denoland/deno_std/blob/93ee52d5a8e2ee1d88153b51a4fda2efa452c9da/node/module.ts#L536-L554

If `module.load()` throws the error is never surfaced.

**Comment by bartlomieju** [comment]
This is actually caused by the fact that `process.exitCode` is not respected when the event loop shuts down "cleanly". Ie. if `process.exitCode` is set anywhere in the code it is not forwarded to Rust in any way.

**Comment by iuioiua** [comment]
@bartlomieju, is this still an issue?

**Comment by bartlomieju** [comment]
To be honest I'm not sure - I haven't tried this example in a while. Any chance you could try to replicate it with `npm:` specifiers?

**Comment by iuioiua** [comment]
```
asher@Ashers-MacBook-Pro-3 deno_std % deno run -A npm:eslint node  

Oops! Something went wrong! :(

ESLint: 8.28.0

ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    npm init @eslint/config

ESLint looked for configuration files in /Users/asher/Documents/GitHub/deno_std/node/testdata and its ancestors. If it found none, it then looked in your home directory.

If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://eslint.org/chat/help
```

**Comment by bartlomieju** [comment]
> npm init @eslint/config via Deno. How is that done?

The equivalent would be `deno run -A npm:@eslint/create-config`

**Comment by kt3k** [comment]
`deno run -A npm:@eslint/create-config` seemed working on my side.

```shellsession
$ deno run -A npm:@eslint/create-config
✔ How would you like to use ESLint? · problems
✔ What type of modules does your project use? · esm
✔ Which framework does your project use? · react
✔ Does your project use TypeScript? · No / Yes
✔ Where does your code run? · browser
✔ What format do you want your config file to be in? · JavaScript
Local ESLint installation not found.
The config that you've selected requires the following dependencies:

eslint-plugin-react@latest eslint@latest
✔ Would you like to install them now? · No / Yes
✔ Which package manager do you want to use? · npm
Installing eslint-plugin-react@latest, eslint@latest

added 156 packages, and audited 157 packages in 6s

66 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Successfully created .eslintrc.js file in /Users/kt3k/tmp/eslint-test
```

**Comment by bartlomieju** [comment]
Okay, let's close it then :)
