### ISSUE TITLE
node: Add child_process.spawnSync

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_std#1654]
Running `eslint --init` and trying to install `typescript-eslint` results in:
```
Oops! Something went wrong! :(

ESLint: 8.2.0

TypeError: cp.spawnSync is not a function
    at Function.spawnSync [as sync] (file:///Users/biwanczuk/dev/eslint_test/node_modules/cross-spawn/index.js:26:23)
    at Object.installSyncSaveDev (file:///Users/biwanczuk/dev/eslint_test/node_modules/eslint/lib/init/npm-utils.js:53:30)
    at installModules (file:///Users/biwanczuk/dev/eslint_test/node_modules/eslint/lib/init/config-initializer.js:424:14)
    at file:///Users/biwanczuk/dev/eslint_test/node_modules/eslint/lib/init/config-initializer.js:460:13
    at async main (file:///Users/biwanczuk/dev/eslint_test/node_modules/eslint/bin/eslint.js:126:9)
```

Caused by missing `child_process.spawnSync` API. Currently we have no way of running subprocesses synchronously in Deno, so the solution to this issue might be quite involved.

**Comment by rinfield** [comment]
unblocked by https://doc.deno.land/deno/unstable@v1.22.1/~/Deno.spawnSync ?

**Comment by iuioiua** [comment]
I'll give this a crack!
