### ISSUE TITLE
node: chalk doesn't work

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_std#1808]
index.js
```js
const chalk = require('chalk')

const test = {
    name: "foo",
};
const p = "*";
const pref = chalk.bold.dim(test.name + p + ' ')
console.log("pref", pref);
```
package.json
```
{
  "name": "test_chalk",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "chalk": "^3.0.0"
  }
}
```

```
$ node index.js
pref foo*
$ deno run --unstable --compat --no-check index.js
error: Uncaught (in promise) TypeError: chalk.bold.dim is not a function
const pref = chalk.bold.dim(test.name + p + ' ')
                        ^
    at Object.<anonymous> (file:///Users/biwanczuk/dev/test_chalk/index.js:7:25)
    at Module._compile (https://deno.land/std@0.120.0/node/module.ts:252:36)
    at Object.Module._extensions..js (https://deno.land/std@0.120.0/node/module.ts:1276:10)
    at Module.load (https://deno.land/std@0.120.0/node/module.ts:231:33)
    at Function._load (https://deno.land/std@0.120.0/node/module.ts:540:14)
    at loadCjsModule ([deno:cli/compat/mod.rs:116:30]:3:22)

```

**Comment by bartlomieju** [comment]
This seems to stem from the fact that Deno doesn't support `__proto__` from Annex B. @kt3k @kitsonk any ideas how we could handle that?
