### ISSUE TITLE
TS2339 [ERROR]: Property 'getUid' does not exist on type 'typeof Deno'.

### ISSUE THREAD

**Issue by idanran** [denoland/deno_std#1927]
**Describe the bug**
```
TS2339 [ERROR]: Property 'getUid' does not exist on type 'typeof Deno'.
    if (Deno.build.os !== "windows" && info.uid === Deno.getUid()) {
                                                         ~~~~~~
    at https://deno.land/std@0.125.0/node/_fs/_fs_access.ts:24:58
```

**Steps to Reproduce**

**Expected behavior**

**Environment**

- OS: Windows11
- deno version: 1.18.2
- std version: 0.125.0

**Comment by crowlKats** [comment]
You need to run with the `--unstable` flag

**Comment by idanran** [comment]
> You need to run with the `--unstable` flag

Ok, thank you.

**Comment by azerpas** [comment]
Happens to me too even with `--unstable`

```
❯ deno run --unstable --import-map import_map.json index.ts
Check file:///Users/azerpas/tests/deno/index.ts
error: TS2339 [ERROR]: Property 'getUid' does not exist on type 'typeof Deno'.
    if (Deno.build.os !== "windows" && info.uid === Deno.getUid()) {
                                                         ~~~~~~
    at https://deno.land/std@0.125.0/node/_fs/_fs_access.ts:24:58
```

**Comment by crowlKats** [comment]
What deno version are you running?

**Comment by azerpas** [comment]
> What deno version are you running?

```
❯ deno --version
deno 1.17.2 (release, x86_64-apple-darwin)
v8 9.7.106.15
typescript 4.5.2
```

**Comment by crowlKats** [comment]
Your version is quite outdated. `getUid` was added in 1.18.2
