### ISSUE TITLE
compat: tap module can't be run

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#2003]
[tap](https://www.npmjs.com/package/tap) is often used by npm-related modules.

When you run `tap` with compat mode, it exits immediately with the error `Cannot add property spawn, object is not extensible` (no stack trace)

**Comment by iuioiua** [comment]
`spawn` is now implemented. This script:
```ts
import tap from "npm:tap";
tap.pass("this is fine");
```
Now throws this error:
```
error: Uncaught TypeError: Cannot read properties of undefined (reading '_compile')
    at Object.exports.install (file:///Users/asher/Library/Caches/deno/npm/registry.npmjs.org/source-map-support/0.5.21/source-map-support.js:562:37)
    at Object.<anonymous> (file:///Users/asher/Library/Caches/deno/npm/registry.npmjs.org/tap/16.3.0/settings.js:6:18)
    at Object.<anonymous> (file:///Users/asher/Library/Caches/deno/npm/registry.npmjs.org/tap/16.3.0/settings.js:64:4)
    at Module._compile (deno:ext/node/02_require.js:712:36)
    at Object.Module._extensions..js (deno:ext/node/02_require.js:745:12)
    at Module.load (deno:ext/node/02_require.js:630:34)
    at Function.Module._load (deno:ext/node/02_require.js:487:14)
    at Module.require (deno:ext/node/02_require.js:652:21)
    at require (deno:ext/node/02_require.js:782:18)
    at Object.<anonymous> (file:///Users/asher/Library/Caches/deno/npm/registry.npmjs.org/tap/16.3.0/lib/tap.js:3:1)
```
