### ISSUE TITLE
deno --fmt failing because parser_typescript.js lambda returns 502 Bad Gateway

### ISSUE THREAD

**Issue by MarkTiedemann** [denoland/deno_std#210]
```
$ deno --fmt ./src/*.ts
Compiling https://deno.land/x/std/prettier/main.ts
Downloading https://deno.land/x/std/prettier/vendor/parser_typescript.js... NOT FOUND
Uncaught NotFound: Cannot resolve module "./vendor/parser_typescript.js" from "/Users/marktiedemann/Library/Caches/deno/deps/https/deno.land/x/std/prettier/prettier.ts"
    at DenoError (deno/js/errors.ts:22:5)
    at maybeError (deno/js/errors.ts:41:12)
    at maybeThrowError (deno/js/errors.ts:29:15)
    at sendSync (deno/js/dispatch.ts:67:5)
    at fetchModuleMetaData (deno/js/os.ts:80:19)
    at _resolveModule (deno/js/compiler.ts:253:38)
    at resolveModuleNames (deno/js/compiler.ts:490:31)
    at compilerHost.resolveModuleNames (deno/third_party/node_modules/typescript/lib/typescript.js:32750:71)
    at resolveModuleNamesWorker (deno/third_party/node_modules/typescript/lib/typescript.js:20688:69)
    at resolveModuleNamesReusingOldState (deno/third_party/node_modules/typescript/lib/typescript.js:20909:20
```

```
$ curl https://deno.land/x/std/prettier/vendor/parser_typescript.js -i
HTTP/1.1 502 Bad Gateway
Content-Type: text/html
Content-Length: 1162
Connection: keep-alive
Server: CloudFront
Date: Wed, 20 Feb 2019 18:25:43 GMT
X-Cache: LambdaValidationError from cloudfront
Via: 1.1 94fa52929d9d55880be2d000b9e472a1.cloudfront.net (CloudFront)
X-Amz-Cf-Id: MsocNiR_NNNdaIvlzeBdZKsLcHkKAYDksuIjuk5VrDCI68QqRsnrww==

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>502 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
The Lambda function returned invalid json: The json output is not parsable.
<BR clear="all"/>
If you received this error while trying to use an app or access a website, please contact the provider or website owner for assistance.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by following steps in the CloudFront documentation
(<A href="https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/http-502-bad-gateway.html">https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/http-502-bad-gateway.html</A>).
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: xKK9PTZaMV_PBSRPagqM7KtYiFO3nvaF2oI9ns_5Sx8EQASN0tX7-w==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
```

**Comment by kt3k** [comment]
(Note: parser_typescript is the biggest file (2.2M) in deno_std)

**Comment by MarkTiedemann** [comment]
I was on a slow hotel WiFi. Could this be some sort of timeout I hit?

**Comment by ry** [comment]
This is due to a bug I've introduced in the deno.land server https://github.com/denoland/registry/pull/62
Trying to resolve this now.

**Comment by ry** [comment]
Should be working now.

**Comment by MarkTiedemann** [comment]
Yep, it's working. Thanks a lot, @ry!
