### ISSUE TITLE
Compilation error of `node/internal_bindings`

### ISSUE THREAD

**Issue by KnorpelSenf** [denoland/deno_std#2108]
**Describe the bug**

The `internal_bindings` modules does not compile.

```bash
error: TS2339 [ERROR]: Property 'ref' does not exist on type 'Listener'.
    this.#listener?.ref();
                    ~~~
    at https://deno.land/std@0.134.0/node/internal_binding/tcp_wrap.ts:240:21

TS2339 [ERROR]: Property 'unref' does not exist on type 'Listener'.
    this.#listener?.unref();
                    ~~~~~
    at https://deno.land/std@0.134.0/node/internal_binding/tcp_wrap.ts:243:21

Found 2 errors.
```

**Steps to Reproduce**

```bash
deno cache https://deno.land/std@0.134.0/node/internal_binding/mod.ts
```

**Expected behavior**

The module compiles.

**Environment**

- OS: Debian 11
- deno version: 1.20.5
- std version: 0.134.0

**Comment by KnorpelSenf** [comment]
That was stupid, it's an unstable API so it obviously needs to be compiled with `--unstable`. Closing.
