### ISSUE TITLE
Property 'ref' does not exist on type 'Listener'

### ISSUE THREAD

**Issue by pasha-bolokhov** [denoland/deno_std#2127]
```
Uncaught TypeError: TS2339 [ERROR]: Property 'ref' does not exist on type 'Listener'.
    this.#listener?.ref();
                    ~~~
    at https://deno.land/std@0.135.0/node/internal_binding/tcp_wrap.ts:240:21

TS2339 [ERROR]: Property 'unref' does not exist on type 'Listener'.
    this.#listener?.unref();
                    ~~~~~
    at https://deno.land/std@0.135.0/node/internal_binding/tcp_wrap.ts:243:21
```

**Steps to Reproduce**
`import { createRequire } from "https://deno.land/std@0.136.0/node/module.ts";`

Similar to https://github.com/denoland/deno_std/issues/2108, but I don't know if should it be considered the same issue…

**Expected behavior**

**Environment**

- OS: Ubuntu 20.04
- deno version: 1.21.0
- std version: 0.136.0

**Comment by mvolfik** [comment]
Previous report of the same error: #2108

I'm also running into this, and using `--unstable` doesn't change anything

**Comment by mvolfik** [comment]
Nevermind: `--unstable` **does** help with deno 1.20.6. I was running 1.17.something before

**Comment by pasha-bolokhov** [comment]
looks like you're right, I'll close this

**Comment by Zamiell** [comment]
I am on the following version of Deno:
```
$ deno --version
deno 1.21.0 (release, x86_64-pc-windows-msvc)
v8 10.0.139.17
typescript 4.6.2
```

When I run the following program:
```ts
import { createRequire } from "https://deno.land/std@0.135.0/node/module.ts";
```

With `deno run deps.ts --unstable`, it gives the following errors:
```
error: TS2339 [ERROR]: Property 'ref' does not exist on type 'Listener'.
    this.#listener?.ref();
                    ~~~
    at https://deno.land/std@0.136.0/node/internal_binding/tcp_wrap.ts:240:21

TS2339 [ERROR]: Property 'unref' does not exist on type 'Listener'.
    this.#listener?.unref();
                    ~~~~~
    at https://deno.land/std@0.136.0/node/internal_binding/tcp_wrap.ts:243:21

TS2345 [ERROR]: Argument of type '{ type: "module"; deno: { namespace: boolean; }; argv?: unknown[] | undefined; env?: Record<string, unknown> | undefined; execArgv?: string[] | undefined; stdin?: boolean | undefined; stdout?: boolean | undefined; ... 5 more ...; workerData?: unknown; }' is not assignable to parameter of type 'WorkerOptions'.
  Object literal may only specify known properties, and 'deno' does not exist in type 'WorkerOptions'.
        deno: { namespace: true },
        ~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.136.0/node/worker_threads.ts:60:9

Found 3 errors.
```
Thus, I believe that this issue should be reopened.

**Comment by Zamiell** [comment]
More info:
When I use the standard library version 0.130.0, the error disappears.
However, versions 0.131.0 through 0.136.0 have various types of errors.

**Comment by pasha-bolokhov** [comment]
Ok, re–opening it…

**Comment by pasha-bolokhov** [comment]
I don't know people, when I use `deno` version `1.21.0` with `--unstable`, with `std@0.136.0` — the error disappears

**Comment by Zamiell** [comment]
It might be a Windows-specific issue then.
