### ISSUE TITLE
compat(node/https): ClientRequest.setTimeout is not a function

### ISSUE THREAD

**Issue by gamer0mega** [denoland/deno_std#2476]
**Describe the bug**

ClientRequest.setTimeout in node/https erroring and saying that it is not a function, which is incompatible with node's https module and will break projects which use the compat mode.

**Steps to Reproduce**

1. Create a file with contents
```js
const https = require('https');
const request = https.request({method: 'GET', host: 'discord.com', path: 'https://discord.com/api/v10/gateway', headers: {"User-Agent": "DiscordBot"}});
request.setTimeout(10000);
request.end();
request.on('response', response => {
  response.on('data', data=>console.log(data.toString()));
  response.on('end', ()=>console.log('ok'));
});
```
2. Run it using the Deno compat mode(it uses the std modules for node defaults)
```js
>deno run -A --compat --unstable httpsTest.js
error: Uncaught (in promise) TypeError: request.setTimeout is not a function
    at Object.<anonymous> (file:///D:/usb/compatTest/httpsTest.js:3:9)
    at Object.<anonymous> (file:///D:/usb/compatTest/httpsTest.js:9:4)
    at Module._compile (https://deno.land/std@0.149.0/node/module.ts:260:36)
    at Object.Module._extensions..js (https://deno.land/std@0.149.0/node/module.ts:1332:10)
    at Module.load (https://deno.land/std@0.149.0/node/module.ts:239:34)
    at Function._load (https://deno.land/std@0.149.0/node/module.ts:558:14)
    at loadCjsModule ([deno:cli\compat\mod.rs:119:30]:3:22)
```

**Expected behavior**

```js
>node httpsTest.js
{"url": "wss://gateway.discord.gg"}
ok
```
The code should return this, as on node.

**Environment**

- OS: Windows 10
- deno version: 1.24.0
- std version: 0.149.0

**Comment by gamer0mega** [comment]
The exact same error occurs when using 
```js
import * as https from 'https://deno.land/std@0.149.0/node/https.ts';
const request = https.request({method: 'GET', host: 'discord.com', path: 'https://discord.com/api/v10/gateway', headers: {"User-Agent": "DiscordBot"}});
request.setTimeout(10000);
request.end();
request.on('response', response => {
  response.on('data', data=>console.log(data.toString()));
  response.on('end', ()=>console.log('ok'));
});
```
I get 
```js
>deno run -A --unstable httpTets.js
error: Uncaught TypeError: request.setTimeout is not a function
request.setTimeout(10000);
        ^
    at file:///D:/usb/compatTest/httpsTest.js:3:9
```

**Comment by gamer0mega** [comment]
Also, there is another bug if you will remove the setTimeout line, due to std having a different url parser, node parses it properly.

**Comment by bartlomieju** [comment]
> Also, there is another bug if you will remove the setTimeout line, due to std having a different url parser. Node parses it properly.

Can you report it as a separate issue?

**Comment by gamer0mega** [comment]
> > Also, there is another bug if you will remove the setTimeout line, due to std having a different url parser. Node parses it properly.
> 
> Can you report it as a separate issue?

I will, just noticed it.

**Comment by iuioiua** [comment]
@luk3skyw4lker, are you still planning on tackling this one? Otherwise, I can give it a crack.

**Comment by luk3skyw4lker** [comment]
@iuioiua You can do it! I didn't manage to see it through

**Comment by lino-levan** [comment]
Any updates @iuioiua? If not, I'd love to take a shot at this one.

**Comment by iuioiua** [comment]
I haven't started work on this. Be my guest! 🤙🏾

**Comment by kt3k** [comment]
@gamer0mega Were you affected by this issue when you are using some actual npm modules in Deno?

**Comment by gamer0mega** [comment]
> @gamer0mega Were you affected by this issue when you are using some actual npm modules in Deno?

This issue is 6 months old and i had it when i tried to use an npm
