### ISSUE TITLE
node - fs.ReadStream - Should work as function in addition to class

### ISSUE THREAD

**Issue by dsherret** [denoland/deno_std#2548]
I ran this test in the CLI, which does `deno run npm:cpy-cli@4.1.0 source.txt destination`:

```rs
#[test]
fn deno_run_esm_module() {
  let _server = http_server();

  let deno_dir = util::new_deno_dir();

  deno_dir.write("source.txt", "test");

  let deno = util::deno_cmd_with_deno_dir(&deno_dir)
    .current_dir(deno_dir.path())
    .arg("run")
    .arg("--unstable")
    .arg("--allow-read")
    .arg("--allow-env")
    .arg("--allow-write")
    .arg("npm:cpy-cli@4.1.0")
    .arg("source.txt")
    .arg("destination")
    .env("NO_COLOR", "1")
    .envs(env_vars())
    .spawn()
    .unwrap();
  let output = deno.wait_with_output().unwrap();
  assert!(output.status.success());

  assert!(deno_dir.path().join("source.txt").exists());
  assert_eq!(deno_dir.read_to_string("destination.txt"), "test");
}
```

And I got:

```
Not implemented: process.on("unhandledRejection")
Cannot copy from `source.txt` to `C:\Users\david\AppData\Local\Temp\deno-cli-test-1661208962749-0\destination\source.txt`: Class constructor ReadStream cannot be invoked without 'new'
```

It seems we use a class for `ReadStream`, but it looks like it works as a function too.

**Comment by iuioiua** [comment]
It appears as though `ReadStream` as a function isn't defined within Node, but rather within the [graceful-fs](https://www.npmjs.com/package/graceful-fs) package [here](https://github.com/isaacs/node-graceful-fs/blob/1f19b0b467e4144260b397343cd60f37c5bdcfda/graceful-fs.js#L297-L302). This was found by testing one of the dependencies, [cpy-file](https://www.npmjs.com/package/cpy-file).

Script:
```ts
// deno run -A --unstable mod.ts  

import { copyFile } from 'npm:cp-file';

await copyFile('source.txt', 'destination.txt');
```
Output:
```
error: Uncaught TypeError: Class constructor ReadStream cannot be invoked without 'new'
    at new ReadStream (file:///Users/asher/Library/Caches/deno/npm/registry.npmjs.org/graceful-fs/4.2.10/graceful-fs.js:299:28)
    at Object.createReadStream (file:///Users/asher/Library/Caches/deno/npm/registry.npmjs.org/graceful-fs/4.2.10/graceful-fs.js:341:12)
    at Module.createReadStream (file:///Users/asher/Library/Caches/deno/npm/registry.npmjs.org/cp-file/10.0.0/fs.js:16:18)
    at copyFileAsync (file:///Users/asher/Library/Caches/deno/npm/registry.npmjs.org/cp-file/10.0.0/index.js:11:30)
    at async file:///Users/asher/Documents/GitHub/x/mod.ts:3:1
```

**Comment by dsherret** [comment]
And that calls fs.ReadStream which errors since our implementation is a class instead of a function?

**Comment by PolarETech** [comment]
Hi,
Can I take this issue?

On my local machine, I have been able to fix it by rewriting the class to function.
If Deno team is okay with the way of rewriting class to function, I would like to submit a PR.

**Comment by kt3k** [comment]
@PolarETech 
I think wrapping with a function can be easier solution than rewriting it in function-style:

For example,
```ts
export function ReadStream(path: string | URL, opts?: ReadStreamOptions) {
  return new ReadStreamImpl(path, opts);
}

export class ReadStreamImpl extends NodeReadable {
...
}
```

And `ReadStream` can be called in the form of both `ReadStream(...)` and `new ReadStream(...)`

**Comment by PolarETech** [comment]
Hi @kt3k

I tried that approach as well, but faced another error:

```bash
error: Uncaught CopyFileError: Cannot read from `./source.txt`: Emitter is not compatible
    at Module.createReadStream (file:///Users/ptech/deno_std/cache/npm/registry.npmjs.org/cp-file/10.0.0/fs.js:21:9)
    at async copyFileAsync (file:///Users/ptech/deno_std/cache/npm/registry.npmjs.org/cp-file/10.0.0/index.js:11:21)
    at async file:///Users/ptech/deno_std/2548.mjs:3:1
```

Trying to add `Object.setPrototypeOf(...)` as following, I got another error.

```bash
export function ReadStream(path: string | URL, opts?: ReadStreamOptions) {
  return new ReadStreamImpl(path, opts);
}

export class ReadStreamImpl extends NodeReadable {
...
}

Object.setPrototypeOf(ReadStream.prototype, NodeReadable.prototype);
// or
Object.setPrototypeOf(ReadStream.prototype, ReadStreamImpl.prototype);
```

```bash
error: Uncaught CopyFileError: Cannot read from `./source.txt`: Cannot read properties of undefined (reading 'endEmitted')
    at Module.createReadStream (file:///Users/ptech/deno_std/cache/npm/registry.npmjs.org/cp-file/10.0.0/fs.js:21:9)
    at async copyFileAsync (file:///Users/ptech/deno_std/cache/npm/registry.npmjs.org/cp-file/10.0.0/index.js:11:21)
    at async file:///Users/ptech/deno_std/2548.mjs:3:1
```

I tested some others, but the only way I could find to fix it was to rewrite the `ReadStream` (and `WriteStream`) from class to function.

**Comment by kt3k** [comment]
Fair enough. Rewriting to function sounds like the only way to make it work. Let's try it.

BTW if ReadStream becomes function, I think it can't be used as the type of ReadStreams. Do you think of any workaround for that?

**Comment by PolarETech** [comment]
I think the following implementation could provide the type. How about it?

```ts
interface ReadStream extends NodeReadable {
  path: string;
}

export function ReadStream(
  this: ReadStream,
  path: string | URL,
  opts?: ReadStreamOptions,
) {
  if (!(this instanceof ReadStream)) {
    return new ReadStream(path, opts);
  }
  ...
  NodeReadable.call(this, {...});
  ...
}

Object.setPrototypeOf(ReadStream.prototype, NodeReadable.prototype);

export function createReadStream(
  path: string | URL,
  opts?: ReadStreamOptions,
): ReadStream {
  return new ReadStream(path, opts);
}
```

**Comment by PolarETech** [comment]
Sorry, I forgot `return this`.
I edited the code in the above comment.

**Comment by kt3k** [comment]
Thanks for the sample code. That structure looks good to me 👍

**Comment by PolarETech** [comment]
Thanks for the confirmation.
I have submitted the PR.
