### ISSUE TITLE
[Feature] `vm.isContext`

### ISSUE THREAD

**Issue by Industrial** [denoland/deno_std#2667]
**Is your feature request related to a problem? Please describe.**
I can't get `jsdom` to work.

```
error: Error: Not implemented: isContext
  throw new Error(message);
        ^
    at notImplemented (https://deno.land/std@0.154.0/node/_utils.ts:23:9)
    at Object.isContext (https://deno.land/std@0.154.0/node/vm.ts:62:3)
    at new Window (file:///home/tom/.cache/deno/npm/registry.npmjs.org/jsdom/20.0.0/lib/jsdom/browser/Window.js:252:10)
    at exports.createWindow (file:///home/tom/.cache/deno/npm/registry.npmjs.org/jsdom/20.0.0/lib/jsdom/browser/Window.js:97:10)
    at new JSDOM (file:///home/tom/.cache/deno/npm/registry.npmjs.org/jsdom/20.0.0/lib/api.js:36:20)
    at file:///home/tom/Code/code9/deno/test-fresh/components/Container.test.tsx:10:36
```

**Describe the solution you'd like**
Implement `vm.isContext` (and probably `vm.createContext`)

**Describe alternatives you've considered**
https://deno.land/manual@v1.25.3/jsx_dom/linkedom
https://deno.land/manual@v1.25.3/jsx_dom/deno_dom

**Comment by lino-levan** [comment]
The following is a quote from https://deno.land/manual@v1.26.1/node
> Node has some built-in modules (e.g. like vm) that are effectively incompatible with the scope of Deno and therefore there aren't easy ways to provide a polyfill of the functionality in Deno.

It sounds to me like the Deno team do not plan to ever support `vm` which is quite sad.

**Comment by bartlomieju** [comment]
`vm` might be implemented once we get support for `ShadowRealm`

**Comment by lino-levan** [comment]
Could you provide some context on `ShadowRealm`? Is there an issue / PR about this?

**Comment by lino-levan** [comment]
Oh never mind, I found https://github.com/denoland/deno/issues/13239, which is an issue tracking support. Linking this here for future reference.

**Comment by andreubotella** [comment]
> Could you provide some context on `ShadowRealm`? Is there an issue / PR about this?

It's a JS API proposal that's currently being worked on: https://github.com/tc39/proposal-shadowrealm

Unlike most new JS APIs that Deno implements automatically because they ship in V8, this one requires some work to support in the internals of Deno. You can follow the work at denoland/deno#13239 (although the work recently had to be rolled back in denoland/deno#16366 because it was blocking certain refactors; it should hopefully be relanded in a couple weeks).

However, `vm` needs some more support in `deno_core` (and maybe `deno_runtime`) than `ShadowRealm` needs, because you cannot cross objects across the realm boundary with `ShadowRealm` but you can with `vm`. This would need a lot of checking that everything is handled correctly, and that certain realm interactions happen properly, that wouldn't be needed with `ShadowRealm`.

**Comment by gregmagdits** [comment]
There is a page in the Deno documentation that states that JSDOM works with Deno, however running the example code on the site generates the same error reported by the OP. The documentation should be updated until this issue is addressed.

**Comment by zuisong** [comment]
It works for me to use jsdom in deno.

```ts
// @deno-types="npm:@types/jsdom"
import { JSDOM } from "https://esm.sh/jsdom@19.0.0?no-check&pin=v64";
export function init() {
  const doc = new JSDOM("");

  window.document = doc.window.document;
  window.TextDecoder = undefined as any;
  window.XPathEvaluator = doc.window.XPathEvaluator;
  window.XPathResult = doc.window.XPathResult;
  window.MutationObserver = doc.window.MutationObserver;
}
```
```ts
import { beforeEach, describe, it } from "deno_std/testing/bdd.ts";
describe("base case", () => {
  beforeEach(() => {
    init();
  });

  it("render dom in deno",() => {
     // language=HTML
  document.body.innerHTML = `<body> </body>`;

  console.log(`
origin html is  ------
${document.documentElement.outerHTML}
------ `);
  });
});


```

**Comment by john-griffin** [comment]
Here are my current findings on JSDOM https://github.com/john-griffin/deno-dom-test
