### ISSUE TITLE
npm compat fs.ReadStream.

### ISSUE THREAD

**Issue by Octo8080X** [denoland/deno_std#2728]
Hello.

I tried use json-server on Deno.
But,  fs.ReadStream will be not work.
How should we respond?

```sh 
$ deno run -A --unstable npm:json-server --host 0.0.0.0 --port 8000 db.json

  \{^_^}/ hi!

  Loading db.json
  Done

  Resources
  http://0.0.0.0:8000/posts
  http://0.0.0.0:8000/comments
  http://0.0.0.0:8000/profile

  Home
  http://0.0.0.0:8000

  Type s + enter at any time to create a snapshot of the database
Some error occurred Error: Not implemented: fs.ReadStream.prototype.constructor with unsupported options ({"maxage":0,"root":"/deno-dir/npm/registry.npmjs.org/json-server/0.17.0/public","start":0,"end":2056})
    at notImplemented (https://deno.land/std@0.153.0/node/_utils.ts:23:9)
    at new ReadStream (https://deno.land/std@0.153.0/node/_fs/_fs_streams.ts:18:7)
    at Object.createReadStream (https://deno.land/std@0.153.0/node/_fs/_fs_streams.ts:54:10)
    at SendStream.stream (file:///deno-dir/npm/registry.npmjs.org/send/0.18.0/index.js:790:19)
    at SendStream.send (file:///deno-dir/npm/registry.npmjs.org/send/0.18.0/index.js:703:8)
    at file:///deno-dir/npm/registry.npmjs.org/send/0.18.0/index.js:770:12
    at Deno.stat.then.denoErrorToNodeError.syscall (https://deno.land/std@0.153.0/node/_fs/_fs_stat.ts:274:15)
```

Best regards.

**Comment by iuioiua** [comment]
@cjihrig, can this ticket be closed? It appears as though this is no longer an issue.

**Comment by kt3k** [comment]
The issue title is no longer valid (the above error doesn't reproduce anymore), but it looks like there are other issues for running `json-server`. I created #2827. Let's track remaining issues there.

**Comment by Octo8080X** [comment]
@cjihrig @iuioiua @kt3k 
Thank you very much. I appreciate it very much.
