### ISSUE TITLE
`npm:tmp` doesn't work

### ISSUE THREAD

**Issue by loynoir** [denoland/deno_std#2796]
**Describe the bug**

**Steps to Reproduce**

```ts
import { file } from "npm:tmp-promise@3.0.3";
const { path, cleanup } = await file();
```
```txt
error: Uncaught Error: OpenOptions requires at least one option to be true
    Deno.open(path, convertFlagAndModeToOptions(flags, mode)).then(
         ^
    at checkOpenOptions (deno:runtime/js/40_files.js:262:13)
    at Object.open (deno:runtime/js/40_files.js:53:18)
    at Object.open (https://deno.land/std@0.158.0/node/_fs/_fs_open.ts:82:10)
    at _tmpNameCreated (registry.npmjs.org/tmp/0.2.1/lib/tmp.js:138:8)
    at registry.npmjs.org/tmp/0.2.1/lib/tmp.js:85:9
    at https://deno.land/std@0.158.0/node/_fs/_fs_stat.ts:275:14
```

**Expected behavior**

**Environment**

- OS: ArchLinux
- deno version: 1.26.0
- std version: 0.158.0

**Comment by iuioiua** [comment]
Hi @loynoir, try upgrading Deno to the latest version. The latest version is 1.26.2 which uses std version 0.160.0, which may have already fixed this issue.

**Comment by loynoir** [comment]
```
$ deno --version
deno 1.26.2 (release, x86_64-unknown-linux-gnu)
v8 10.7.193.16
typescript 4.8.3
$ deno run --unstable -A reproduce.ts
error: Uncaught NotFound: No such file or directory (os error 2), open '/tmp/tmp-20828-OdrKL0MTjJHa'
    at async Object.open (deno:runtime/js/40_files.js:55:17)
$ deno run --unstable -A reproduce.ts
error: Uncaught NotFound: No such file or directory (os error 2), open '/tmp/tmp-20964-59FN6sb5ITn2'
    at async Object.open (deno:runtime/js/40_files.js:55:17)
```

**Comment by iuioiua** [comment]
Perhaps, instead, you could do the following:
```ts
const path = await Deno.makeTempFile();
...
await Deno.remove(path); // Cleanup
```
