### ISSUE TITLE
Node compat test suite is failing on Windows

### ISSUE THREAD

**Issue by cjihrig** [denoland/deno_std#2807]
**Describe the bug**

Starting with https://github.com/denoland/deno_std/commit/820474d600c5e1f612f08165d2b21c678e9692a0, the Windows CI has been failing consistently with the errors below. Nothing jumps out on the std side, so I'm thinking maybe it could be a change in core causing the failures here.

```
Node.js compatibility "parallel\test-net-allow-half-open.js" => ./node/_tools/test.ts:46:8
error: AssertionError: Failed assertion: error: Uncaught Error: read ECONNRESET
    Error.captureStackTrace(err);
          ^
    at __node_internal_captureLargerStackTrace (file:///C:/a/deno_std/deno_std/node/internal/errors.ts:113:11)
error: Test failed
    at __node_internal_errnoException (file:///C:/a/deno_std/deno_std/node/internal/errors.ts:194:10)
    at TCP.onStreamRead [as onread] (file:///C:/a/deno_std/deno_std/node/internal/stream_base_commons.ts:279:20)
    at TCP.#read (file:///C:/a/deno_std/deno_std/node/internal_binding/stream_wrap.ts:298:12)

    throw new AssertionError(msg);
          ^
    at assert (file:///C:/a/deno_std/deno_std/testing/asserts.ts:139:11)
    at fail (file:///C:/a/deno_std/deno_std/testing/asserts.ts:582:3)
    at fn (file:///C:/a/deno_std/deno_std/node/_tools/test.ts:92:9)

Node.js compatibility "parallel\test-net-socket-close-after-end.js" => ./node/_tools/test.ts:46:8
error: AssertionError: Failed assertion: error: Uncaught AssertionError
    Error.captureStackTrace(this, stackStartFn || stackStartFunction);
          ^
    at new AssertionError (file:///C:/a/deno_std/deno_std/node/assertion_error.ts:532:11)
    at toNode (file:///C:/a/deno_std/deno_std/node/assert.ts:77:15)
    at assert (file:///C:/a/deno_std/deno_std/node/assert.ts:95:3)
    at Socket.<anonymous> (file:///C:/a/deno_std/deno_std/node/_tools/test/parallel/test-net-socket-close-after-end.js:28:5)
    at Socket.emit (file:///C:/a/deno_std/deno_std/node/_events.mjs:379:28)
    at file:///C:/a/deno_std/deno_std/node/net.ts:1424:14
    at deno:core/01_core.js:236:9

    throw new AssertionError(msg);
          ^
    at assert (file:///C:/a/deno_std/deno_std/testing/asserts.ts:139:11)
    at fail (file:///C:/a/deno_std/deno_std/testing/asserts.ts:582:3)
    at fn (file:///C:/a/deno_std/deno_std/node/_tools/test.ts:92:9)

 FAILURES 

Node.js compatibility "parallel\test-net-allow-half-open.js" => ./node/_tools/test.ts:46:8
Node.js compatibility "parallel\test-net-socket-close-after-end.js" => ./node/_tools/test.ts:46:8
```

**Environment**
CI. I don't have a Windows setup to test locally.

**Comment by bartlomieju** [comment]
I suspect it might be related to https://github.com/denoland/deno/commit/c061538417cdb2b0a8f2d6eae7f5f11511ba34fe I got some unexpected network errors in another context. CC @lucacasonato I think we should revert that change and revist after v1.27 release.
