### ISSUE TITLE
bug: `serveDirIndex TLS` test is flaky on macOS

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#2874]
```
serveDirIndex TLS => ./http/file_server_test.ts:455:6
error: ConnectionRefused: Connection refused (os error 61)
    const conn = await Deno.connectTls({
                 ^
    at async Object.connectTls (deno:ext/net/02_tls.js:37:42)
    at async file:///Users/runner/work/deno_std/deno_std/http/file_server_test.ts:459:18
```

**Comment by kt3k** [comment]
related https://github.com/denoland/deno_std/issues/1750

This flakiness exists for long time...

**Comment by iuioiua** [comment]
Oh! Didn't see that...
