### ISSUE TITLE
`run npm:prisma studio` command requires `--unstable` in `node/internal_binding/tcp_wrap.ts`

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#2883]
The command `deno run -A --node-modules-dir npm:prisma@4.6 studio` still requires `--unstable` flag to work. It errors the below when invoked without `--unstable`:

```
Error: TypeError: this[#listener].unref is not a function
    at TCP.unref (file:///Users/kt3k/denoland/deno_std/node/internal_binding/tcp_wrap.ts:236:22)
    at Server.unref (file:///Users/kt3k/denoland/deno_std/node/net.ts:2379:20)
    at Server._setupListenHandle [as _listen2] (file:///Users/kt3k/denoland/deno_std/node/net.ts:1939:10)
    at _listenInCluster (file:///Users/kt3k/denoland/deno_std/node/net.ts:1666:12)
    at Server.listen (file:///Users/kt3k/denoland/deno_std/node/net.ts:2149:9)
```

**Comment by bartlomieju** [comment]
Let's just stabilize `ref()` and `unref()` methods. I'm not sure why we didn't do that for 1.28 :/

**Comment by kt3k** [comment]
ref and unref are now stabilized.
