### ISSUE TITLE
bug(node): setup script failure

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#2907]
**Describe the bug**

1. Change `nodeVersion` in `node/_tools/config.json` to `18.12.1`.
2. Run `deno task node:setup -n`. The following error will occur:
```
Task node:setup deno run --allow-read --allow-net --allow-write node/_tools/setup.ts "-n"
Downloading https://nodejs.org/dist/v18.12.1/node-v18.12.1.tar.gz in path "versions/node-v18.12.1.tar.gz" ...
Downloaded: https://nodejs.org/dist/v18.12.1/node-v18.12.1.tar.gz into versions/node-v18.12.1.tar.gz
Decompressing node-v18.12.1.tar.gz...
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '__wbindgen_add_to_stack_pointer')
        wasm.__wbindgen_add_to_stack_pointer(16);
             ^
    at gunzip (https://deno.land/x/denoflate@2.0.2/wasm/pkg/foras.js:224:14)
    at decompressTests (file:///Users/asher/Documents/GitHub/deno_std/node/_tools/setup.ts:113:29)
    at async file:///Users/asher/Documents/GitHub/deno_std/node/_tools/setup.ts:277:3
```
3. Change `nodeVersion` in `node/_tools/config.json` back to `18.12.0` (original value).
4. Run `deno task node:setup -n`. The above error will occur again, but for v18.12.0:
```
Task node:setup deno run --allow-read --allow-net --allow-write node/_tools/setup.ts "-n"
Downloading https://nodejs.org/dist/v18.12.0/node-v18.12.0.tar.gz in path "versions/node-v18.12.0.tar.gz" ...
Downloaded: https://nodejs.org/dist/v18.12.0/node-v18.12.0.tar.gz into versions/node-v18.12.0.tar.gz
Decompressing node-v18.12.0.tar.gz...
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '__wbindgen_add_to_stack_pointer')
        wasm.__wbindgen_add_to_stack_pointer(16);
             ^
    at gunzip (https://deno.land/x/denoflate@2.0.2/wasm/pkg/foras.js:224:14)
    at decompressTests (file:///Users/asher/Documents/GitHub/deno_std/node/_tools/setup.ts:113:29)
    at async file:///Users/asher/Documents/GitHub/deno_std/node/_tools/setup.ts:277:3
```

**Environment**
std version = main branch of `deno_std` as of writing this issue.
```
deno 1.28.0 (release, x86_64-apple-darwin)
v8 10.9.194.1
typescript 4.8.3
```

**Comment by iuioiua** [comment]
That's not the case for me:
```
asher@Ashers-MacBook-Air deno_std % deno task node:setup -n
Task node:setup deno run --allow-read --allow-net --allow-write node/_tools/setup.ts "-n"
Downloading https://nodejs.org/dist/v18.12.0/node-v18.12.0.tar.gz in path "versions/node-v18.12.0.tar.gz" ...
Downloaded: https://nodejs.org/dist/v18.12.0/node-v18.12.0.tar.gz into versions/node-v18.12.0.tar.gz
Decompressing node-v18.12.0.tar.gz...
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '__wbindgen_add_to_stack_pointer')
        wasm.__wbindgen_add_to_stack_pointer(16);
             ^
    at gunzip (https://deno.land/x/denoflate@2.0.2/wasm/pkg/foras.js:224:14)
    at decompressTests (file:///Users/asher/Documents/GitHub/deno_std/node/_tools/setup.ts:113:29)
    at async file:///Users/asher/Documents/GitHub/deno_std/node/_tools/setup.ts:277:3
```

**Comment by cjihrig** [comment]
> `asher@Ashers-MacBook-Air deno_std % deno task node:setup -n`

Can you remove that `-n` from the end.

**Comment by PolarETech** [comment]
Hi,

I have recently set up a new Mac and have had the same error.
It seems to be failing to decompress the "node-v18.12.0.tar.gz".
Here is the procedure to reproduce it.

1. Execute the command `rm -r node/_tools/versions`
2. Execute the command `deno task node:setup`
3. See error
```zsh
% deno task node:setup
Task node:setup deno run --allow-read --allow-net --allow-write node/_tools/setup.ts
Downloading https://nodejs.org/dist/v18.12.0/node-v18.12.0.tar.gz in path "versions/node-v18.12.0.tar.gz" ...
Downloaded: https://nodejs.org/dist/v18.12.0/node-v18.12.0.tar.gz into versions/node-v18.12.0.tar.gz
Decompressing node-v18.12.0.tar.gz...
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '__wbindgen_add_to_stack_pointer')
        wasm.__wbindgen_add_to_stack_pointer(16);
             ^
    at gunzip (https://deno.land/x/denoflate@2.0.2/wasm/pkg/foras.js:224:14)
    at decompressTests (file:///Users/ptech/deno_std/node/_tools/setup.ts:113:29)
    at async file:///Users/ptech/deno_std/node/_tools/setup.ts:277:3
```

After the above steps, the versions directory is as follows: "node-v18.12.0.tar.gz" is not decompressed.

```zsh
% ls node/_tools/versions
node-v18.12.0.tar.gz
```

https://github.com/denoland/deno_std/blob/3832a1f3c06260c403d23255795cf30b4439dc61/node/_tools/setup.ts#L4

Changing this URL back to `https://deno.land/x/denoflate@1.2.1/mod.ts`, which is the same as before e808ece, will successfully decompress the file.
Is it conceivable that denoflate@2.0.2 could be the cause of the issue?

__Environments__

```
deno 1.28.1 (release, aarch64-apple-darwin)
v8 10.9.194.1
typescript 4.8.3
```

**Comment by iuioiua** [comment]
> It seems to work if you don't specify the `-n` flag.

Sorry @cjihrig , I realise now what you said. Yes, I've tried with no `-n` defined either and it still doesn't work.

> Is it conceivable that denoflate@2.0.2 could be the cause of the issue?

Yes, @PolarETech, the issue is definitely with denoflate. For some reason, the `wasm` variable is undefined. Now that I think about it, I'll open a ticket in the denoflat repo.

**Comment by iuioiua** [comment]
Accidental close, sorry.
