### ISSUE TITLE
TLSSocket._start seems never set

### ISSUE THREAD

**Issue by dsherret** [denoland/deno_std#2909]
**Describe the bug**

https://github.com/denoland/deno_std/blob/bc345306e520e758e8af9b00144c393c9c066c52/node/_tls_wrap.ts#L373

**Steps to Reproduce**

```
import sql from "npm:mssql";

const connectionPool = new sql.ConnectionPool({
  server: "localhost",
  database: "Kia",
  user: "user",
  password: "password",
  options: {
    trustedConnection: true,
    trustServerCertificate: true,
  },
});

const connection = await connectionPool.connect();
console.log("Connected");
```

**Expected behavior**

Should work.

**Environment**

- OS: Windows 10
- deno version: 1.28.1
- std version: 1.165.0

**Comment by superted17** [comment]
If it helps, here is another scenario in which this issue can also be seen:

```
import Imap from 'https://esm.sh/imap@0.8.19';

const imapConfig: Imap.Config = {
  user: 'redacted',
  password: 'redacted',
  host: 'redacted',
  port: 993,
  tls: true
};

const imap = new Imap(imapConfig);

imap.once('ready', () => {
  console.info('ready');
});

imap.once('error', (err: Error) => {
  console.error(err);
});
 
imap.once('end', () => {
  console.info('Connection ended');
});

imap.connect();
```

Error stack trace:

```
❯ deno run --allow-env index.ts                                                                                                                                                           ─╯
error: Uncaught TypeError: tlssock._start is not a function
    tlssock._start();
            ^
    at Object.connect (https://deno.land/std@0.153.0/node/_tls_wrap.ts:365:13)
    at d.connect (https://esm.sh/v96/imap@0.8.19/deno/imap.js:3:1490)
    at file:///home/ed/code/incoming-email/index.ts:27:6
```

**Comment by mpacers** [comment]
I found the relevant Node code: https://github.com/nodejs/node/blob/main/lib/_tls_wrap.js#L952

```
TLSSocket.prototype._start = function() {
  debug('%s _start',
        this._tlsOptions.isServer ? 'server' : 'client',
        'handle?', !!this._handle,
        'connecting?', this.connecting,
        'requestOCSP?', !!this._tlsOptions.requestOCSP,
  );
  if (this.connecting) {
    this.once('connect', this._start);
    return;
  }

  // Socket was destroyed before the connection was established
  if (!this._handle)
    return;

  if (this._tlsOptions.requestOCSP)
    this._handle.requestOCSP();
  this._handle.start();
};
```

It calls `this._handle.start()` which doesn't seem to be implemented yet. It looks like `this._handle` is a Socket but it doesn't have a `start` method. Currently, the Node Compat version `_tls_wrap.ts` is less than 1/3 the number of lines as the Node version `_tls_wrap.js`, so I'm not sure how close it is to functioning in Deno, but I'd very much like to help get it working and will continue digging into it.

**Comment by kt3k** [comment]
`npm:nodemailer` seems having the same problem #3035
