### ISSUE TITLE
Cannot resolve module "deno" (NOT FOUND)

### ISSUE THREAD

**Issue by sundowndev** [denoland/deno_std#296]
On this line

https://github.com/denoland/deno_std/blob/master/http/server.ts#L2

Get his error : 

```
Downloading https://deno.land/x/http@v0.3.0/deno... NOT FOUND
Uncaught NotFound: Cannot resolve module "deno" from "/home/sundowndev/.cache/deno/deps/https/deno.land/x/http@v0.3.0/server.ts"
    at DenoError (deno/js/errors.ts:22:5)
    at maybeError (deno/js/errors.ts:33:12)
    at maybeThrowError (deno/js/errors.ts:39:15)
    at sendSync (deno/js/dispatch.ts:75:5)
    at fetchModuleMetaData (deno/js/os.ts:80:19)
    at _resolveModule (deno/js/compiler.ts:249:38)
    at resolveModuleNames (deno/js/compiler.ts:479:35)
    at compilerHost.resolveModuleNames (deno/third_party/node_modules/typescript/lib/typescript.js:118650:138)
    at resolveModuleNamesWorker (deno/third_party/node_modules/typescript/lib/typescript.js:86767:127)
    at resolveModuleNamesReusingOldState (deno/third_party/node_modules/typescript/lib/typescript.js:87001:24)
```

https://deno.land/x/http@v0.3.0/deno gives a 404 error.

deno: 0.3.3
v8: 7.4.238
typescript: 3.3.3333

**Comment by kt3k** [comment]
'deno' builtin module is removed at deno@v0.3.3. You need to update the import path to `https://deno.land/std@v0.3.2/http/server.ts`

**Comment by sundowndev** [comment]
The issue was from this file https://deno.sh/abc@v0.1.0/package.ts
Nevermind.
