### ISSUE TITLE
`deno run npm:0x` throws `acorn.Parser.extend(...).extend is not a function`

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno_std#2964]
```js
// hello.mjs
console.log("Hello flamegraph!");
```
```
deno run --allow-read --allow-env --allow-sys npm:0x -- hello.mjs
error: Uncaught TypeError: acorn.Parser.extend(...).extend is not a function
    at Object.<anonymous> (file:///home/gjzwiers/.cache/deno/npm/registry.npmjs.org/acorn-node/1.8.2/index.js:6:4)
    at Object.<anonymous> (file:///home/gjzwiers/.cache/deno/npm/registry.npmjs.org/acorn-node/1.8.2/index.js:40:4)
    at Module._compile (deno:ext/node/02_require.js:726:36)
    at Object.Module._extensions..js (deno:ext/node/02_require.js:759:12)
    at Module.load (deno:ext/node/02_require.js:643:34)
    at Function.Module._load (deno:ext/node/02_require.js:500:14)
    at Module.require (deno:ext/node/02_require.js:665:21)
    at require (deno:ext/node/02_require.js:799:18)
    at Object.<anonymous> (file:///home/gjzwiers/.cache/deno/npm/registry.npmjs.org/detective/5.2.1/index.js:1:265)
    at Object.<anonymous> (file:///home/gjzwiers/.cache/deno/npm/registry.npmjs.org/detective/5.2.1/index.js:82:4)
```

I found a closed issue with a similar error: https://github.com/denoland/deno_std/issues/723

```
deno --version

deno 1.28.2+623dbe7 (canary, x86_64-unknown-linux-gnu)
v8 10.9.194.5
typescript 4.8.3
```

OS: WSL 2 (Ubuntu)

**Comment by kt3k** [comment]
`acorn-node` uses `__proto__` (https://github.com/browserify/acorn-node/blob/v1.8.2/lib/class-fields/index.js#L25), which currently Deno doesn't support even in npm compat layer.

**Comment by kt3k** [comment]
`0x` seems depending on `acorn-node` 1.x very heavily:

```
   - "0x#nanohtml" depends on it
   - Hoisted from "0x#nanohtml#acorn-node"
   - Hoisted from "0x#browserify#syntax-error#acorn-node"
   - Hoisted from "0x#nanohtml#transform-ast#acorn-node"
   - Hoisted from "0x#browserify#insert-module-globals#acorn-node"
   - Hoisted from "0x#browserify#insert-module-globals#undeclared-identifiers#acorn-node"
   - Hoisted from "0x#browserify#module-deps#detective#acorn-node"
```
