### ISSUE TITLE
Docs: semver page not working

### ISSUE THREAD

**Issue by raspo** [denoland/deno_std#2994]
**Describe the bug**

The page dedicated to the `semver` module https://deno.land/std@0.167.0/semver/mod.ts isn't working on the official STD documentation website.

It shows this error:
<img width="616" alt="CleanShot 2022-12-09 at 14 15 29@2x" src="https://user-images.githubusercontent.com/927264/206804464-0081c363-d779-428b-81dd-5a049d7ab8eb.png">

It seems like it broke in `v0.167.0` (the previous version [works fine](https://deno.land/std@0.166.0/semver/mod.ts))

**Steps to Reproduce**

1. visit https://deno.land/std@0.167.0/semver/mod.ts

or 

1. go to https://deno.land/std@0.167.0?doc
2. click on `semver`

**Expected behavior**

The documentation page should be accessible like in version 0.166.0 https://deno.land/std@0.166.0/semver/mod.ts

**Comment by lino-levan** [comment]
Super weird, I believe this is a bug with https://github.com/denoland/deno_doc or https://github.com/denoland/dotland. I will do some investigation.

**Comment by lino-levan** [comment]
This is definitely an error with [denoland/dotland](https://github.com/denoland/dotland). I'm getting this error when I open semver on a dev environment:

```
An error occurred during route handling or page rendering. Error: Unknown language: `bnf` is not registered
    at a (https://esm.sh/v87/fault@2.0.1/deno/fault.js:2:307)
    at Object.u [as highlight] (https://esm.sh/v87/lowlight@2.7.0/deno/lowlight.js:2:2810)
    at syntaxHighlight (https://deno.land/x/deno_doc_components@0.4.0/doc/markdown.tsx:30:27)
    at Object.mdToHtml (https://deno.land/x/deno_doc_components@0.4.0/doc/markdown.tsx:97:10)
    at Object.Markdown (https://deno.land/x/deno_doc_components@0.4.0/doc/markdown.tsx:135:26)
    at https://esm.sh/v94/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1626
    at E (https://esm.sh/v94/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1653)
    at E (https://esm.sh/v94/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1729)
    at E (https://esm.sh/v94/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:2578)
    at E (https://esm.sh/v94/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:2578)
```

This error occurs due to [this line](https://github.com/denoland/deno_std/blob/6bd933286079d9afbb588092e963e0565c230dfb/semver/mod.ts#L189), which defines the language of the language block as `bnf` which I guess is not a valid language for the syntax highlighting that we are using. If the language is not recognized, we should probably just default to no syntax highlighting instead of throwing an error.

**Comment by lino-levan** [comment]
It turns out that this is a known bug, https://github.com/denoland/dotland/issues/2616. Should this issue remain open until this bug is resolved?

**Comment by raspo** [comment]
Thank you @lino-levan for the prompt response and sorry if I opened the issue in the wrong place.
To be honest, it wasn't very clear to me which project controls the API docs since it seems to be mostly auto-generated and the older version worked, so this led me here...

**Comment by lino-levan** [comment]
No worries, I think it's not super well obvious unless you've been in the community for a little bit. Thanks for reporting the bug!
