### ISSUE TITLE
`tlssock._start is not a function` when trying to use nodemailer 

### ISSUE THREAD

**Issue by dehrhard** [denoland/deno_std#3035]
**Describe the bug**
I'm trying to use `nodemailer` for an email service. `createTransport` works but if I try to call `transport.sendMail`. I receive the Error: `Error initiating TLS - tlssock._start is not a function`. 
It looks like it happens in nodemailer when it tries to upgrade the connection in `_upgradeConnection`. In there it is calling `tls.connect` where `tls` is the native node module.
So it looks like the `_start` function is not polyfilled

**Steps to Reproduce**
1. Create Transport
```
import { createTransport } from 'npm:nodemailer';
const transport = createTransport({
  host,
  port,
  auth: {
    user,
    pass,
  },
});
```
2. try to send mail
```
transport.sendMail({
  to: '',
  from: '',
  ...
})
```

3. Error:
```
Failed in send Mail procedure
 Error: Error initiating TLS - tlssock._start is not a function
    at file:///home/dehrhard/.cache/deno/npm/registry.npmjs.org/nodemailer/6.8.0/lib/smtp-connection/index.js:1370:31
    at SMTPConnection._upgradeConnection (file:///home/dehrhard/.cache/deno/npm/registry.npmjs.org/nodemailer/6.8.0/lib/smtp-connection/index.js:905:20)
    at SMTPConnection._actionSTARTTLS (file:///home/dehrhard/.cache/deno/npm/registry.npmjs.org/nodemailer/6.8.0/lib/smtp-connection/index.js:1368:14)
    at SMTPConnection._processResponse (file:///home/dehrhard/.cache/deno/npm/registry.npmjs.org/nodemailer/6.8.0/lib/smtp-connection/index.js:953:20)
    at SMTPConnection._onData (file:///home/dehrhard/.cache/deno/npm/registry.npmjs.org/nodemailer/6.8.0/lib/smtp-connection/index.js:755:14)
    at Socket.SMTPConnection._onSocketData (file:///home/dehrhard/.cache/deno/npm/registry.npmjs.org/nodemailer/6.8.0/lib/smtp-connection/index.js:193:44)
    at Socket.emit (https://deno.land/std@0.167.0/node/_events.mjs:379:28)
    at _t (https://deno.land/std@0.167.0/node/_stream.mjs:10:32972)
    at ir (https://deno.land/std@0.167.0/node/_stream.mjs:10:32699)
    at Socket.w.push (https://deno.land/std@0.167.0/node/_stream.mjs:10:31925)
```

**Expected behavior**
I would expect `sendMail` to correctly work as expected in node

**Environment**

- OS:  Ubuntu 22.04
- deno version: 1.28.3
- std version:0.167.0

**Comment by kt3k** [comment]
Let's track in https://github.com/denoland/deno/issues/18303
