### ISSUE TITLE
TOML module cannot parse strings with #s

### ISSUE THREAD

**Issue by kevinkassimo** [denoland/deno_std#310]
Example: for the following file
```ts
import { parse } from "https://deno.land/std/toml/parser.ts"

console.log(parse(`
s = "123#456"
`))
```

Actual output:
```
Uncaught SyntaxError: Invalid or unexpected token
    at _parseData (file:///Users/kun/Library/Caches/deno/deps/https/deno.land/std/toml/parser.ts:247:17)
    at _processDeclaration (file:///Users/kun/Library/Caches/deno/deps/https/deno.land/std/toml/parser.ts:183:21)
    at _parseLines (file:///Users/kun/Library/Caches/deno/deps/https/deno.land/std/toml/parser.ts:290:23)
    at parse (file:///Users/kun/Library/Caches/deno/deps/https/deno.land/std/toml/parser.ts:309:10)
    at parse (file:///Users/kun/Library/Caches/deno/deps/https/deno.land/std/toml/parser.ts:317:33)
    at file:///Users/kun/Projects/Deno/test/toml.ts:3:13
```

Expected behavior:
```
{ s: "123#456" }
```

I think we might have split with `#` prematurely here:
https://github.com/denoland/deno_std/blob/fa1664e6ccaad9ad98a131f03fdd600c5fa24100/toml/parser.ts#L29-L39

cc @zekth

**Comment by zekth** [comment]
Working on a fix
