### ISSUE TITLE
useless error infomation

### ISSUE THREAD

**Issue by loynoir** [denoland/deno_std#3166]
**Describe the bug**

**Steps to Reproduce**

```js
import { readFile } from 'https://deno.land/std@0.175.0/node/fs/promises.ts'
await readFile('notExists')
```

```
error: Uncaught NotFound: No such file or directory (os error 2)
    at async Object.readFile (deno:runtime/js/40_read_file.js:25:20)
```

**Expected behavior**

```js
import { readFile } from 'fs/promises'
await readFile('notExists')
```

```txt
node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^

[Error: ENOENT: no such file or directory, open 'notExists'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'notExists'
}

Node.js v18.13.0
```

**Environment**

- OS: [e.g. Ubuntu 20.04, MacOS 11]
- deno version:
- std version:

**Comment by kamilogorek** [comment]
Should be mostly fixed with https://github.com/denoland/deno/pull/17710. Note that `node:fs` is internally calling `Deno.readFile`, so the change there, will propagate here.

**Comment by kt3k** [comment]
Addressed in https://github.com/denoland/deno/pull/17719 (Thanks to @kamilogorek )

Now the above script shows the below error:
```
error: Uncaught NotFound: No such file or directory (os error 2), readfile 'notExists'
    at async Object.readFile (ext:deno_fs/30_fs.js:695:18)
```
