### ISSUE TITLE
`npm:dockerode@3.3.4` got type error

### ISSUE THREAD

**Issue by loynoir** [denoland/deno_std#3203]
**Describe the bug**

**Steps to Reproduce**

```ts
> var Docker = (await import('npm:dockerode@3.3.4')).default
undefined
> var docker = new Docker({socketPath: '/var/run/docker.sock'});
undefined
> await docker.listContainers()
Uncaught TypeError: error sending request for url (http://localhost/containers/json): error trying to connect: tcp connect error: Connection refused (os error 111)
    at async mainFetch (internal:ext/fetch/26_fetch.js:267:14)
    at async fetch (internal:ext/fetch/26_fetch.js:491:9)
    at async ClientRequest._final (https://deno.land/std@0.177.0/node/http.ts:147:7)
```

**Expected behavior**

```ts
> var Docker = (await import('dockerode')).default
undefined
> var docker = new Docker({socketPath: '/var/run/docker.sock'});
undefined
> await docker.listContainers()
[
  {
    Id: ...
```

**Environment**

- OS: [e.g. Ubuntu 20.04, MacOS 11] ArchLinux
- deno version: 1.30.3
- std version: https://deno.land/std@0.177.0/node/http.ts:147:7

**Comment by loynoir** [comment]
### minimal reproduce
```js
void http.request(
  'http://localhost/version',
  {
    socketPath: '/var/run/docker.sock',
  },
  (res) => res.on('data', (c) => console.log('' + c)),
).end()
```

### Expected
```sh
$ node
> void http.request('http://localhost/version', {socketPath: '/var/run/docker.sock'}, (res)=>res.on('data',c=>console.log(''+c))).end()
// {"Platform": ...
```

### Actual
```sh
$ deno
> import http from 'node:http'
> void http.request('http://localhost/version', {socketPath: '/var/run/docker.sock'}, (res)=>res.on('data',c=>console.log(''+c))).end()
// nothing
