### ISSUE TITLE
dotenv: allowEmptyValues option doesn't prevent uncaught error

### ISSUE THREAD

**Issue by satyarohith** [denoland/deno_std#3211]
```
➜  cat .env                 
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: .env   <EMPTY>
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
➜  cat .env.example  
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: .env.example
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ EXAMPLE=true
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
➜  cat main.ts     
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: main.ts
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ import { loadSync } from "https://deno.land/std/dotenv/mod.ts";
   2   │ 
   3   │ loadSync({ allowEmptyValues: true });
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
➜  deno run -A main.ts                 
error: Uncaught MissingEnvVarsError: The following variables were defined in the example file but are not present in the environment:
  EXAMPLE

Make sure to add them to your env file.
    throw new MissingEnvVarsError(
          ^
    at assertSafe (https://deno.land/std@0.177.0/dotenv/mod.ts:362:11)
    at loadSync (https://deno.land/std@0.177.0/dotenv/mod.ts:231:5)
    at file:///Users/sr/p/std_env/main.ts:3:1
```
**Describe the bug**

`dotenv` throws an error even when the `allowEmptyValues` option is set to true. 

**Expected behavior**

It shouldn't throw an uncaught exception error when the `allowEmptyValues` option is set to true.

**Environment**

```
deno 1.30.3 (release, aarch64-apple-darwin)
v8 10.9.194.5
typescript 4.9.4
std: 0.177.0
```

**Comment by kamilogorek** [comment]
`allowEmptyValues` is, as the name says, for empty values, not missing keys :)

```
EXAMPLE=
```

This will work with `{ allowEmptyValues: true }`, yet fail without it.

**Comment by denizdogan** [comment]
I think this can be closd
