### ISSUE TITLE
ipv6 http server: connection reset by peer on many simultaneous requests

### ISSUE THREAD

**Issue by tjjfvi** [denoland/deno_std#3250]
**Describe the bug**

Requests to the http server will non-deterministically fail with "connection reset by peer" when many simultaneous requests are made.

**Steps to Reproduce**

```ts
// serve.ts

import { serve } from "https://deno.land/std@0.179.0/http/mod.ts"

serve(() => new Response("foo bar baz", {}), { hostname: "[::]" })
```

```ts
// overload.ts

Promise.all(Array.from(
  { length: 10000 },
  () => fetch("http://localhost:8000/"),
))
```

```sh
deno run -A serve.ts &
deno run -A overload.ts
```

The latter command will sometimes (~ 1 in 10) fail with
```
error: Uncaught (in promise) TypeError: error sending request for url (http://localhost:8000/): error trying to connect: tcp connect error: Connection reset by peer (os error 54)
    at async mainFetch (internal:deno_fetch/26_fetch.js:269:12)
    at async fetch (internal:deno_fetch/26_fetch.js:493:7)
    at async Promise.all (index 4511)
```

Running `overload.ts` with e.g. Node results in an analogous error, so I believe the issue is on the server side.

**Expected behavior**

The http server should support many simultaneous connections.

**Environment**

- OS: MacOS 13.2
- deno version: 1.31.2 (release, aarch64-apple-darwin)
- std version: 0.179.0

**Comment by lino-levan** [comment]
Are you able to reproduce this bug with the new `Deno.serve` api?
