### ISSUE TITLE
`std@0.180.0/json` broken links in the examples from the source files

### ISSUE THREAD

**Issue by woosaaahh** [denoland/deno_std#3259]
**Describe the bug**

Hi everyone !

Since `std@0.180.0` some packages have been moved to the top-level (`csv / json / toml / yaml / ...`). 
It appears that the `testdata` directory previously in `<std>/encoding/testdata` was moved to `<std>/json/testdata`.

However, the updates are not reported in the example codes included in the source files.
The urls to fetch the json test files use the old paths and throw `SyntaxError` due to the '404 Not found' response.
```
error: Uncaught (in promise) SyntaxError: Unexpected non-whitespace character after JSON at position 4 (parsing: '404 Not Found')
      throw new (error.constructor as ErrorConstructor)(
            ^
    at parse (https://deno.land/std@0.180.0/json/_common.ts:12:13)
    at Object.transform (https://deno.land/std@0.180.0/json/json_parse_stream.ts:67:32)
    at Module.invokeCallbackFunction (ext:deno_webidl/00_webidl.js:862:16)
    at TransformStreamDefaultController.transformAlgorithm (ext:deno_web/06_streams.js:3411:14)
    at transformStreamDefaultControllerPerformTransform (ext:deno_web/06_streams.js:3685:59)
    at transformStreamDefaultSinkWriteAlgorithm (ext:deno_web/06_streams.js:3763:10)
    at WritableStreamDefaultController.writeAlgorithm (ext:deno_web/06_streams.js:528:12)
    at writableStreamDefaultControllerProcessWrite (ext:deno_web/06_streams.js:4045:55)
    at writableStreamDefaultControllerAdvanceQueueIfNeeded (ext:deno_web/06_streams.js:3948:5)
    at writableStreamDefaultControllerWrite (ext:deno_web/06_streams.js:4092:3)
```

Here is a list I collected of those "broken links" after _grepping_ for `encoding/testdata` : 
https://github.com/denoland/deno_std/blob/main/encoding/json/stream.ts#L37
https://github.com/denoland/deno_std/blob/main/encoding/json/stream.ts#L64
https://github.com/denoland/deno_std/blob/main/encoding/json/stream.ts#L84
https://github.com/denoland/deno_std/blob/main/json/json_parse_stream.ts#L22
https://github.com/denoland/deno_std/blob/main/json/json_parse_stream.ts#L42
https://github.com/denoland/deno_std/blob/main/json/concatenated_json_parse_stream.ts#L18

**Steps to Reproduce**

- run the example from https://deno.land/std@0.180.0/json/mod.ts?s=ConcatenatedJsonParseStream
- run the examples from https://deno.land/std@0.180.0/json/mod.ts?s=JsonParseStream
- run the examples from https://deno.land/std@0.180.0/json/mod.ts?s=JsonStringifyStream
- run the example from https://deno.land/std@0.180.0/encoding/json/stream.ts?doc=&s=ConcatenatedJsonParseStream
- run the examples from https://deno.land/std@0.180.0/encoding/json/stream.ts?doc=&s=JsonParseStream
- run the examples from https://deno.land/std@0.180.0/encoding/json/stream.ts?doc=&s=JsonStringifyStream

**Expected behavior**

No http 404 errors.

**Environment**

- OS: ArchLinux
- deno version: 1.31.3
- std version: 0.180.0

**Comment by iuioiua** [comment]
I'll take this one.
