### ISSUE TITLE
A fresh checkout results in failing tests?

### ISSUE THREAD

**Issue by gaggle** [denoland/deno_std#3571]
I wanted to look into what I think might be a date-related bug but checking out the repo and following the contributing steps results in failing tests. I'm not sure what I'm doing wrong, any help appreciated.

**Steps to Reproduce**

1. Checkout the repo
    ```sh
    $ git status
    On branch main
    Your branch is up to date with 'origin/main'.
    ```
2. Init submodule
    ```sh
    $ git submodule update --init
    $ git submodule status
     aa121de88de512680fe5752f0e9bfc07e311854c wasi/testdata (aa121de)
    ```
3. Run tests
    ```sh
    $ deno task test
    Task test deno test --doc --unstable --allow-all --parallel --coverage=./cov
    ./assert/assert_exists_test.ts => AssertExists ... ok (7ms)
    ./assert/assert_equals_test.ts => pass case ... ok (7ms)
    ...
    ./testing/snapshot_test.ts => SnapshotTest - createAssertSnapshot ... Composite ... ok (5ms)
    ./testing/snapshot_test.ts => SnapshotTest - createAssertSnapshot ... ok (26ms)
    
     ERRORS
    
    [std/datetime] dayOfYear => ./datetime/day_of_year_test.ts:189:6
    error: AssertionError: Values are not equal.
    
    
        [Diff] Actual / Expected
    
    
    -   90
    +   91
    
      throw new AssertionError(message);
            ^
        at assertEquals (file:///Users/gaggle/Projects/deno_std/assert/assert_equals.ts:53:9)
        at fn (file:///Users/gaggle/Projects/deno_std/datetime/day_of_year_test.ts:202:5)
    
     FAILURES
    
    [std/datetime] dayOfYear => ./datetime/day_of_year_test.ts:189:6
    
    FAILED | 1835 passed (2359 steps) | 1 failed | 11 ignored (24s)
    
    error: Test failed
    ```

**Expected behavior**

Tests to run to completion

**Environment**

- OS: MacOS Ventura 13.5 (22G74), Intel Core i7
- deno version: 
    ```sh
    $ deno --version
    deno 1.36.2 (release, x86_64-apple-darwin)
    v8 11.7.439.1
    typescript 5.1.6
    ```

- std version: Does this refer to the sha of this repo I'm on?
    ```sh
    git rev-parse HEAD
    ee6856c2ed955e44cff6eb16c673f16642799fe6
    ```

**Comment by lino-levan** [comment]
I've experienced this locally, I was wondering the same exact thing. It works in CI which is weird. Is this fixed in Deno canary? No idea.

**Comment by jollytoad** [comment]
I've seen this too, it looks like it may fail depending on your locale & timezone.

I'm in the UK, and we're in BST atm (UTC+01:00), so if get the date in the test:

```ts
const date = new Date("2007-04-01T00:00:00.000Z");

data.toLocaleString();
// output: "01/04/2007, 01:00:00"

const yearStart = new Date(date);
yearStart.setFullYear(date.getFullYear(), 0, 0);

yearStart.toISOString();
// output: "2006-12-31T01:00:00.000Z"

const diff = date.getTime() - yearStart.getTime();

diff/86400000
// output: 90.95833333333331
// so Math.floor will round down to: 90
```

I don't know what the logic is meant to be for various timezones/locales, but I hope this insight may help.

**Comment by jollytoad** [comment]
I think ideally the date/time tests probably need to be run as if in various timezones and during periods of temporary adjustments (ie. daylight saving), but I have no idea how you'd apply that to this test suite.
