### ISSUE TITLE
Env tests are flaky when setting environment

### ISSUE THREAD

**Issue by dsherret** [denoland/deno_std#3658]
```
load when multiple files => ./dotenv/load_test.ts:30:6
error: AssertionError: Values are not equal.


    [Diff] Actual / Expected


-   Do not override!
+   hello world


  throw new AssertionError(message);
        ^
    at assertEquals (file:///V:/deno_std/assert/assert_equals.ts:53:9)
    at fn (file:///V:/deno_std/dotenv/load_test.ts:45:5)
```

It seems one test is doing `Deno.env.set("GREETING", "Do not override!");`, which affects this test depending on what order the files get run in (I think).

**Comment by iuioiua** [comment]
@dsherret, are you still getting this issue?

**Comment by kt3k** [comment]
Should be fixed by https://github.com/denoland/deno_std/pull/3644

Closing
