### ISSUE TITLE
dayOfYear test fails on my machine

### ISSUE THREAD

**Issue by dsherret** [denoland/deno_std#3659]
```
[std/datetime] dayOfYear => ./datetime/day_of_year_test.ts:189:6
error: AssertionError: Values are not equal.


    [Diff] Actual / Expected


-   73
+   74

  throw new AssertionError(message);
        ^
    at assertEquals (file:///V:/deno_std/assert/assert_equals.ts:53:9)
    at fn (file:///V:/deno_std/datetime/day_of_year_test.ts:201:5)
```

**Comment by lino-levan** [comment]
Related / duplicate of #3571
