### ISSUE TITLE
TypeError: Module not found "https://deno.land/std/hash/mod.ts".

### ISSUE THREAD

**Issue by ralyodio** [denoland/deno_std#3780]
Warning Implicitly using latest version (0.205.0) for https://deno.land/std/hash/mod.ts
TypeError: Module not found "https://deno.land/std/hash/mod.ts".
    at https://deno.land/x/god_crypto@v0.2.0/src/eme_oaep.ts:1:28
    at async ClientSQLite._migrationHandler (https://deno.land/x/nessie@2.0.11/clients/AbstractClient.ts:246:37)
    at async ClientSQLite._migrate (https://deno.land/x/nessie@2.0.11/clients/AbstractClient.ts:103:7)
    at async ClientSQLite.migrate (https://deno.land/x/nessie@2.0.11/clients/ClientSQLite.ts:107:5)
    at async Command.migrate [as fn] (https://deno.land/x/nessie@2.0.11/cli/commands.ts:138:3)
    at async Command.execute (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1794:7)
    at async Command.parseCommand (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1639:14)
    at async cli (https://deno.land/x/nessie@2.0.11/cli.ts:29:3)
    at async run (https://deno.land/x/nessie@2.0.11/cli.ts:139:5)
    at async https://deno.land/x/nessie@2.0.11/cli.ts:158:1 {
  code: "ERR_MODULE_NOT_FOUND"
}

**Comment by crowlKats** [comment]
std/hash is not available anymore since over a year.

**Comment by ralyodio** [comment]
what do i use in its replacement?

**Comment by lino-levan** [comment]
It seems like `nessie` is using a comically old version of `god_crypto` which for some reason did not pin the standard library at the time. This is a bug with `nessie` and should probably be reported.

**Comment by lino-levan** [comment]
It looks like Nessie is unmaintained (https://github.com/halvardssm/deno-nessie/issues/165). The author recommends that you use Prisma instead.

**Comment by iuioiua** [comment]
Yes, `std/hash` was removed a while ago. Lino's suggestion seems like a good one.
