### ISSUE TITLE
datetime/parse: cannot parse ISO week date

### ISSUE THREAD

**Issue by scarf005** [denoland/deno_std#3928]
**Describe the bug**

parse() cannot parse [ISO week date](https://en.wikipedia.org/wiki/ISO_week_date) such as `2023-W50`.

**Steps to Reproduce**
```
import { parse } from "https://deno.land/std@0.208.0/datetime/parse.ts"

parse("2023-W50", "yyyy-MM-dd")
```

**Expected behavior**

it returns `2023-12-11`. however, it errors with

```
Uncaught Error: value not valid for token { month undefined } W20
    at DateTimeFormatter.parseToParts (https://deno.land/std@0.208.0/datetime/_common.ts:562:15)
    at parse (https://deno.land/std@0.208.0/datetime/parse.ts:28:27)
    at <anonymous>:1:22

```

**Environment**

- OS: Ubuntu 23.10
- deno version: 1.38.5+e9ab9ba canary
- std version: 0.208.0

**Comment by timreichen** [comment]
I think one would use `ww` tokens e.g. `parse("2023-W50", "yyyy-ww")`. But they are not supported atm.

**Comment by syhol** [comment]
Is the datetime module deprecated? because https://github.com/denoland/deno_std/pull/3615 suggests that it is.

**Comment by kt3k** [comment]
We are planning to deprecate what overlaps with [Temporal](https://tc39.es/proposal-temporal/docs/) when it's shipped to V8

**Comment by iuioiua** [comment]
See https://github.com/denoland/deno/pull/21738

**Comment by jsejcksn** [comment]
> See https://github.com/denoland/deno/pull/21738

@iuioiua I don't think the Temporal proposal supports ISO week dating at this point. Ref:

- https://github.com/js-temporal/proposal-temporal-v2/issues/11

**Comment by iuioiua** [comment]
Ah, yes. I was looking at the spec and wondering about that. Thanks for the reference! I'll submit a PR shortly that more definitively defines what these `std/datetime` deprecations would look like. Anyway... That's enough hijacking this issue 😆

**Comment by timreichen** [comment]
@iuioiua https://github.com/denoland/deno_std/pull/4198
