### ISSUE TITLE
readMIMEHeader exception: malformed MIME header line

### ISSUE THREAD

**Issue by irustm** [denoland/deno_std#409]
```
Host: localhost:8000
Connection: keep-alive
Content-Length: 136
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
Cache-Control: no-cache
Origin: chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
Postman-Token: a5b88a02-b7af-2296-42ba-a9c33ed4206f
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryimeZ2Le9LjohiUiG
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
Content-Disposition: form-data; name="test"

------WebKitFormBoundaryimeZ2Le9LjohiUiG--
C:/Users/User/AppData/Local/deno/deps/https/raw.githubusercontent.com/denoland/deno_std/master/textproto/mod.ts:86:22
                throw new ProtocolError(`malformed MIME header line: ${str(kv)}`);
                      ^
Uncaught ProtocolError: malformed MIME header line: ------WebKitFormBoundaryimeZ2Le9LjohiUiG--
```

**Comment by zekth** [comment]
Is your cache up to date for deno_std?
Could you run it with `--reload` ?

**Comment by irustm** [comment]
Yeah, I've tried the latest version, too.

**Comment by irustm** [comment]
and 
```
C:/Users/User/AppData/Local/deno/deps/https/raw.githubusercontent.com/denoland/deno_std/master/textproto/mod.ts:88:22
                throw new ProtocolError(`malformed MIME header line: ${str(kv)}`);
                      ^
Uncaught ProtocolError: malformed MIME header line: POST /home/post HTTP/1.1
```

**Comment by runnerSnail** [comment]
```shell
Uncaught ProtocolError: malformed MIME header initial line:     "title":"课2程",
    at ProtocolError (file:///Users/waniu/Library/Caches/deno/deps/https/deno.land/std@v0.3.4/textproto/mod.ts:20:5)
    at readMIMEHeader (file:///Users/waniu/Library/Caches/deno/deps/https/deno.land/std@v0.3.4/textproto/mod.ts:79:13)
```

**Comment by runnerSnail** [comment]
I made the same mistake

**Comment by ry** [comment]
I'm unable to repeat this error. If you're able to trigger this exception reliably, please copy and paste the exact HTTP request.

You can attempt to put the request into one of these tests:
https://github.com/denoland/deno_std/blob/c2f5a7cf2206a9a476e0e9b116db00ced327f188/textproto/reader_test.ts#L147-L167
and see if you can trigger a failure.

**Comment by zekth** [comment]
I can reproduce. Working on it.
