### ISSUE TITLE
bug(log): `RotatingFileHandler.log()` should handle message longer than 4096

### ISSUE THREAD

**Issue by yuqiang-yuan** [denoland/deno_std#4361]
**Is your feature request related to a problem? Please describe.**

I'm using `file_handler` to log user's payload which sometimes longer than 4096 bytes. but the `file_handler` can not handle it correctly. the error message is:

```
error: Uncaught (in promise) RangeError: offset is out of bounds
    this._buf.set(bytes, this._pointer);
              ^
    at Uint8Array.set (<anonymous>)
    at RotatingFileHandler.log (https://deno.land/std@0.216.0/log/file_handler.ts:79:15)
    at RotatingFileHandler.log (https://deno.land/std@0.216.0/log/rotating_file_handler.ts:106:11)
    at RotatingFileHandler.handle (https://deno.land/std@0.216.0/log/base_handler.ts:28:10)
    at RotatingFileHandler.handle (https://deno.land/std@0.216.0/log/file_handler.ts:66:11)
    at https://deno.land/std@0.216.0/log/logger.ts:135:15
```

**Describe the solution you'd like**

I home file log handler could handle messages longer than 4096. If the message is longer than 4096, split it into chunks and then write to the log file and flush.

**Comment by babiabeo** [comment]
This issue was fixed by #4415.
