### ISSUE TITLE
`csv/parse_test.ts` has type errors, but they are not caught in CI

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#4606]
The file has type errors, but they are not caught in CI. (`deno task test` doesn't error at them)

```shellsession
$ deno check csv/parse_test.ts
Check file:///Users/kt3k/denoland/deno_std/csv/parse_test.ts
error: TS2345 [ERROR]: Argument of type 'undefined' is not assignable to parameter of type 'ParseOptions'.
      const parsed = parse("a\nb", undefined);
                                   ~~~~~~~~~
    at file:///Users/kt3k/denoland/deno_std/csv/parse_test.ts:828:36

TS2793 [ERROR]:     The call would have succeeded against this implementation, but implementation signatures of overloads are not externally visible.
    export function parse<const T extends ParseOptions>(
                    ~~~~~
        at file:///Users/kt3k/denoland/deno_std/csv/parse.ts:353:17

TS2344 [ERROR]: Type 'false' does not satisfy the constraint 'true'.
      type _ = AssertTrue<IsExact<typeof parsed, string[][]>>;
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///Users/kt3k/denoland/deno_std/csv/parse_test.ts:829:27

Found 2 errors.
```

**Comment by iuioiua** [comment]
Perhaps, we should implement #3706.
