### ISSUE TITLE
Uncaught error when the listener is closed

### ISSUE THREAD

**Issue by zhmushan** [denoland/deno_std#465]
**Version:** v0.7.0

**Code:**
```ts
import { serve } from "https://deno.land/std@v0.7.0/http/server.ts";
const s = serve("0.0.0.0:8080");
async function main() {
  for await (const req of s) {
    s.close();
    req.respond({ body: new TextEncoder().encode("Hello World\n") });
  }
  console.log("end")
}
main();
```
**Expected behavior:**
```
end
```
**Actual behavior:**
```
Uncaught Other: Listener has been closed
    at DenoError (js/errors.ts:22:5)
    at maybeError (js/errors.ts:33:12)
    at handleAsyncMsgFromRust (js/dispatch.ts:41:17)
    at handleAsyncMsgFromRust (shared_queue.js:157:9)
```

**Comment by motss** [comment]
This might be related https://github.com/denoland/deno_std/issues/386

**Comment by sholladay** [comment]
It seems that this is still happening. Makes it difficult to implement graceful shutdown for a Deno server.
