### ISSUE TITLE
Leaks detected with ` await new FakeTime().runMicrotasks();`

### ISSUE THREAD

**Issue by jeiea** [denoland/deno_std#4929]
**Steps to Reproduce**

```ts
import { FakeTime } from "jsr:@std/testing/time";

Deno.test("When setTimeout and clearTimeout", async (test) => {
  const id = setTimeout(() => {}, 1000);
  console.log(`set timeout ${id}`);

  await test.step("it should not leak", async () => {
    await new FakeTime().runMicrotasks();
    clearTimeout(id);
    console.log(`clearing timeout ${id}`);
  });
});
```

**Expected behavior**

```
ok | 1 passed (1 step) | 0 failed (2ms)
```

**Actual behavior**

```
 *  Executing task: C:\ProgramData\chocolatey\lib\deno\deno.EXE test --allow-all --no-check --trace-leaks --filter /^When setTimeout and clearTimeout$/ d:\Repos\jeiea\deno_report\main.ts 

running 1 test from ./main.ts
When setTimeout and clearTimeout ...
------- output -------
set timeout 1
----- output end -----
  it should not leak ...
------- output -------
clearing timeout 1
----- output end -----
  it should not leak ... ok (1ms)
When setTimeout and clearTimeout ... FAILED (2ms)

 ERRORS 

When setTimeout and clearTimeout => ./main.ts:3:6
error: Leaks detected:
  - A timer was started in this test, but never completed. This is often caused by not calling `clearTimeout`. The operation was started here:
    at Object.queueUserTimer (ext:core/01_core.js:738:9)
    at setTimeout (ext:deno_web/02_timers.js:61:15)
    at file:///D:/Repos/jeiea/deno_report/main.ts:4:14
    at innerWrapped (ext:cli/40_test.js:191:11)
    at exitSanitizer (ext:cli/40_test.js:107:33)
    at outerWrapped (ext:cli/40_test.js:134:20)

 FAILURES 

When setTimeout and clearTimeout => ./main.ts:3:6

FAILED | 0 passed (1 step) | 1 failed (18ms)
```

**Environment**

- OS:  Windows 11 Pro 10.0.22631 N/A Build 22631 x64
- deno version: 1.44.0
- std version:  0.224.0

**Comment by kt3k** [comment]
You need to call `.restore()` of fakeTime to restore `clearTimeout` function.

```ts
import { FakeTime } from "jsr:@std/testing/time";

Deno.test("When setTimeout and clearTimeout", async (test) => {
  const id = setTimeout(() => {}, 1000);
  console.log(`set timeout ${id}`);

  await test.step("it should not leak", async () => {
    const fakeTime = new FakeTime();
    await fakeTime.runMicrotasks();
    fakeTime.restore();
    clearTimeout(id);
    console.log(`clearing timeout ${id}`);
  });
});
```

**Comment by jeiea** [comment]
If someone else makes the same mistake, please upvote this issue.
