### ISSUE TITLE
std lib imports require version

### ISSUE THREAD

**Issue by MarkTiedemann** [denoland/deno_std#534]
Works fine:

```typescript
// test.ts
import * as fs from "https://deno.land/std@v0.11.0/fs/mod.ts";
```

Fails with cryptic error:

```typescript
// test.ts
import * as fs from "https://deno.land/std/fs/mod.ts";
```

```sh
$ deno test.ts
Compile file:///Users/$user/dev/deno_intro/test.ts
error: Uncaught ImportPathPrefixMissing: relative import path not prefixed with / or ./ or ../
► js/errors.ts:33:12
    at DenoError (js/errors.ts:22:5)
    at maybeError (js/errors.ts:33:12)
    at maybeThrowError (js/errors.ts:39:15)
    at sendSync (js/dispatch.ts:137:5)
    at fetchModuleMetaData (js/compiler.ts:137:19)
    at _resolveModule (js/compiler.ts:254:12)
    at js/compiler.ts:370:37
    at resolveModuleNames (js/compiler.ts:368:24)
    at resolveModuleNamesWorker (third_party/node_modules/typescript/lib/typescript.js:89230:127)
    at resolveModuleNamesReusingOldState (third_party/node_modules/typescript/lib/typescript.js:89473:24)
```

I think this is kinda unexpected, especially since some of the documentation in the std lib is using unversioned imports.

**Comment by ry** [comment]
I can't repeat the problem.

**Comment by MarkTiedemann** [comment]
`rm -rf ~/Library/Caches/deno` fixed the error. I guess this was due to an older version of `.../fs/mod.ts`. Perhaps a caching issue?
