### ISSUE TITLE
std/http multitable req.respond throw error: BrokenPipe: Broken pipe (os error 32)

### ISSUE THREAD

**Issue by ngot** [denoland/deno_std#663]
## Reproduce code

```js
import {
  listenAndServe,
} from "https://deno.land/std/http/server.ts";

const body = "Hello World\n";
const options = { port: 3000 };
listenAndServe(options, (req) => {
  for (let i = 0; i < 100; i++) {
    req.respond({ body });
  }
});
```

## Error

```
error: Uncaught BrokenPipe: Broken pipe (os error 32)   
    at unwrapResponse ($deno$/ops/dispatch_minimal.ts:63:11)
    at Object.sendAsyncMinimal ($deno$/ops/dispatch_minimal.ts:106:10)
    at async Object.write ($deno$/ops/io.ts:65:18)
    at async BufWriter.flush (https://deno.land/std/io/bufio.ts:475:25)
    at async writeResponse (https://deno.land/std/http/_io.ts:274:3)
    at async ServerRequest.respond (https://deno.land/std/http/server.ts:97:7)
```

## Analysis

The underneath HTTP connection has been closed when trying to write data into it.

## Suggestion

Node.js uses a `finished` tag to indicates whether the response has responded or not. https://github.com/nodejs/node/blob/master/lib/_http_outgoing.js#L817

Maybe Deno can do those similar things.

**Comment by bartlomieju** [comment]
`std/http` implementation was rewritten to leverage native HTTP bindings available in Deno (`Deno.serveHttp`). This error should no longer occur. I'm going to tentatively close this issue, please let me know if the problem persists.
