### ISSUE TITLE
Getting error. " No constituent of type 'ExportValue' is callable."

### ISSUE THREAD

**Issue by reselbob** [denoland/deno_std#697]
Hi:

I have Katacoda scenario I made the runs a Rust WASM binary in Deno. I was working fine.

It is here:

https://katacoda.com/reselbob/scenarios/demo-rust-wasm

Here are the particulars on the Deno version

```
deno 1.7.1 (release, x86_64-unknown-linux-gnu)
v8 8.9.255.3
typescript 4.1.3
```

Now, when I execute the Deno `main.ts` that contains this code:

```
const wasmCode = await Deno.readFile("./target/wasm32-unknown-unknown/debug/wasm_deno_example.wasm");
const wasmModule = new WebAssembly.Module(wasmCode);
const wasmInstance = new WebAssembly.Instance(wasmModule);
const {
    square,
} = wasmInstance.exports;

console.log(square(1));
console.log(square(2));
console.log(square(3));
console.log(square(4));

```

Get this error:

```
Check file:///root/wasm_deno_example/main.ts
error: TS2349 [ERROR]: This expression is not callable.
  No constituent of type 'ExportValue' is callable.
console.log(square(1));
            ~~~~~~
    at file:///root/wasm_deno_example/main.ts:8:13

TS2349 [ERROR]: This expression is not callable.
  No constituent of type 'ExportValue' is callable.
console.log(square(2));
            ~~~~~~
    at file:///root/wasm_deno_example/main.ts:9:13

TS2349 [ERROR]: This expression is not callable.
  No constituent of type 'ExportValue' is callable.
console.log(square(3));
            ~~~~~~
    at file:///root/wasm_deno_example/main.ts:10:13

TS2349 [ERROR]: This expression is not callable.
  No constituent of type 'ExportValue' is callable.
console.log(square(4));
            ~~~~~~
    at file:///root/wasm_deno_example/main.ts:11:13
```

It was working and now it's not. I don't even know where to start. Can you help me? I hope so.

**Comment by reselbob** [comment]
Also, this article seems to be broken too:

https://www.telerik.com/blogs/how-to-compile-rust-into-webassembly-run-in-deno

**Comment by reselbob** [comment]
Tell me please, do I need to add this line:

`const main = wasmInstance.exports.main as CallableFunction`

As shown here: https://deno.land/manual/getting_started/webassembly

**Comment by reselbob** [comment]
Yes, this is the fix:

```
const wasmCode = await Deno.readFile("./target/wasm32-unknown-unknown/debug/wasm_deno_example.wasm");
const wasmModule = new WebAssembly.Module(wasmCode);
const wasmInstance = new WebAssembly.Instance(wasmModule);

const square = wasmInstance.exports.square as CallableFunction

console.log(square(1));
console.log(square(2));
console.log(square(3));
console.log(square(4));

```
