### ISSUE TITLE
ws: Uncaught ConnectionAborted in writeFrame

### ISSUE THREAD

**Issue by elisee** [denoland/deno_std#736]
Using ws@0.87.0, I sometimes get this error (happened on Windows 10). Looks like it happens when there was a frame in the queue but the socket has been disconnected in the meantime.

```
error: Uncaught (in promise) ConnectionAborted: An established connection was aborted by the software in your host machine. (os error 10053)
      throw new ErrorClass(res.err.message);
            ^
    at unwrapResponse (deno:runtime/js/10_dispatch_minimal.js:60:13) 
    at sendAsync (deno:runtime/js/10_dispatch_minimal.js:99:12)      
    at async write (deno:runtime/js/12_io.js:118:20)
    at async Object.writeAll (deno:runtime/js/13_buffer.js:224:19)   
    at async BufWriter.flush (bufio.ts:468:7)
    at async writeFrame (mod.ts:144:3)
```

Points to this: https://github.com/denoland/deno_std/blob/6a3446d0cf1875384f98dfda5154a5a022f74f53/ws/mod.ts#L144

I don't think it's catchable from the user's perspective as `writeFrame()`is async, but it's called from `dequeue()` which is sync.

**Comment by elisee** [comment]
I think I was wrong about this, `dequeue()` catches errors through the promise returned by `writeFrame()`. Looks like my code was at fault for not handling the error.
