### ISSUE TITLE
BUG: assertEquals and assertArrayIncludes fails on Ubuntu but not on MacOS

### ISSUE THREAD

**Issue by halvardssm** [denoland/deno_std#796]
When running tests in the MacOS terminal, it passes, but when running on Linux (Debian/Ubuntu), it fails.

```shell
AssertionError: actual: "[
  "1000000000000-test.ts => 20010909014640-test.ts",
  "10000000000000-test.ts => 22861120174640-test.ts",
  "1587937822648-test.ts => 20200426215022-test.ts",
  "999999999999-test.ts => 20010909014639-test.ts",
  "9999999999999-test.ts => 22861120174639-test.ts",
]" expected to include: "[
  "9999999999999-test.ts => 22861120184639-test.ts",
  "1587937822648-test.ts => 20200426235022-test.ts",
  "999999999999-test.ts => 20010909034639-test.ts",
  "10000000000000-test.ts => 22861120184640-test.ts",
  "1000000000000-test.ts => 20010909034640-test.ts",
]"
missing: [
  "9999999999999-test.ts => 22861120184639-test.ts",
  "1587937822648-test.ts => 20200426235022-test.ts",
  "999999999999-test.ts => 20010909034639-test.ts",
  "10000000000000-test.ts => 22861120184640-test.ts",
  "1000000000000-test.ts => 20010909034640-test.ts",
]
    at assertArrayIncludes (https://deno.land/std@0.89.0/testing/asserts.ts:435:9)
    at fn (file:///workspaces/deno-nessie/tests/update_timestamps/update_timestamps.test.ts:62:5)
    at async asyncOpSanitizer (deno:runtime/js/40_testing.js:38:9)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:74:7)
    at async Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:101:9)
    at async TestRunner.[Symbol.asyncIterator] (deno:runtime/js/40_testing.js:275:13)
    at async Object.runTests (deno:runtime/js/40_testing.js:352:22)
    at async file:///workspaces/deno-nessie/$deno$test.ts:3:1
```

```shell
AssertionError: Values are not equal:


    [Diff] Actual / Expected


    [
-     "1000000000000-test.ts => 20010909014640-test.ts",
-     "10000000000000-test.ts => 22861120174640-test.ts",
-     "1587937822648-test.ts => 20200426215022-test.ts",
-     "999999999999-test.ts => 20010909014639-test.ts",
-     "9999999999999-test.ts => 22861120174639-test.ts",
+     "1000000000000-test.ts => 20010909034640-test.ts",
+     "10000000000000-test.ts => 22861120184640-test.ts",
+     "1587937822648-test.ts => 20200426235022-test.ts",
+     "999999999999-test.ts => 20010909034639-test.ts",
+     "9999999999999-test.ts => 22861120184639-test.ts",
    ]

    at assertEquals (https://deno.land/std@0.89.0/testing/asserts.ts:219:9)
    at fn (file:///workspaces/deno-nessie/tests/update_timestamps/update_timestamps.test.ts:62:5)
    at async asyncOpSanitizer (deno:runtime/js/40_testing.js:38:9)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:74:7)
    at async Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:101:9)
    at async TestRunner.[Symbol.asyncIterator] (deno:runtime/js/40_testing.js:275:13)
    at async Object.runTests (deno:runtime/js/40_testing.js:352:22)
    at async file:///workspaces/deno-nessie/$deno$test.ts:3:1
```

To recreate, you can checkout [this branch](https://github.com/halvardssm/deno-nessie/tree/timestamps) and run `make test-cli-update-timestamps`.

The branch also includes a devcontainer to use with VSCode for convenience.

**Comment by caspervonb** [comment]
Not a bug with assertions, it's doing what it is supposed to do.

Inputs:

```ts
{
  actual: [
    "1000000000000-test.ts => 20010909014640-test.ts",
    "9999999999999-test.ts => 22861120174639-test.ts",
    "999999999999-test.ts => 20010909014639-test.ts",
    "1587937822648-test.ts => 20200426215022-test.ts",
    "10000000000000-test.ts => 22861120174640-test.ts"
  ],
  expected: [
    "9999999999999-test.ts => 22861120184639-test.ts",
    "1587937822648-test.ts => 20200426235022-test.ts",
    "999999999999-test.ts => 20010909034639-test.ts",
    "10000000000000-test.ts => 22861120184640-test.ts",
    "1000000000000-test.ts => 20010909034640-test.ts"
  ]
}
```

Resulting in:
```console
AssertionError: actual: "[
  "1000000000000-test.ts => 20010909014640-test.ts",
  "9999999999999-test.ts => 22861120174639-test.ts",
  "999999999999-test.ts => 20010909014639-test.ts",
  "1587937822648-test.ts => 20200426215022-test.ts",
  "10000000000000-test.ts => 22861120174640-test.ts",
]" expected to include: "[
  "9999999999999-test.ts => 22861120184639-test.ts",
  "1587937822648-test.ts => 20200426235022-test.ts",
  "999999999999-test.ts => 20010909034639-test.ts",
  "10000000000000-test.ts => 22861120184640-test.ts",
  "1000000000000-test.ts => 20010909034640-test.ts",
]"
missing: [
  "9999999999999-test.ts => 22861120184639-test.ts",
  "1587937822648-test.ts => 20200426235022-test.ts",
  "999999999999-test.ts => 20010909034639-test.ts",
  "10000000000000-test.ts => 22861120184640-test.ts",
  "1000000000000-test.ts => 20010909034640-test.ts",
]
```

Would be great if you could narrow it down to the actual problem!

**Comment by halvardssm** [comment]
Could you elaborate? The weird part is that it passes on OS X but not on Debian. Is this intended?

I'll try to debug this further 💪🏻

**Comment by caspervonb** [comment]
> The weird part is that it passes on OS X but not on Debian. Is this intended?

Might be a difference in timer resolution, not entirely sure what your CLI is doing.

**Comment by halvardssm** [comment]
Long story short, it updates filenames from using milliseconds, to use datetime. But the assert only compares the strings and arrays, no? It shouldn't have anything to say with the timer resolution, but maybe it has something to do with the encoding/decoding?

**Comment by kt3k** [comment]
When looking at these diffs carefully,
```diff
-     "1000000000000-test.ts => 20010909014640-test.ts",
-     "10000000000000-test.ts => 22861120174640-test.ts",
-     "1587937822648-test.ts => 20200426215022-test.ts",
-     "999999999999-test.ts => 20010909014639-test.ts",
-     "9999999999999-test.ts => 22861120174639-test.ts",
+     "1000000000000-test.ts => 20010909034640-test.ts",
+     "10000000000000-test.ts => 22861120184640-test.ts",
+     "1587937822648-test.ts => 20200426235022-test.ts",
+     "999999999999-test.ts => 20010909034639-test.ts",
+     "9999999999999-test.ts => 22861120184639-test.ts",
```

the timestamps seem having difference of 1 or 2 hours. Do your macOS and Debian machines have the same timezone setup?
