### ISSUE TITLE
Can't access AssertionError message in catch block

### ISSUE THREAD

**Issue by heyheyhello** [denoland/deno_std#800]
Hi, I'm trying to use Deno's nice assert message formatting (colours, etc). I have a few `assert()` and `assertStrictEquals()` that need to survive a for-loop. I tried a try/catch like this:

```ts
for (const binary of binaries) {
  // Modify the binary:
  // <...>
  
  // Check I did it correctly:
  let ok = true;
  const a = (
    assertion: typeof assert | typeof assertStrictEquals,
    ...args: unknown[]
  ) => {
    try {
      // @ts-ignore
      assertion(...args);
    } catch (e) {
      ok = false;
      console.log(e); // Doesn't work?
    }
  };
  const layoutFinal = readBinaryLayout(binary);
  a(assert, layoutFinal.compilePayload !== false);
  a(assert, layoutFinal.embedPayload !== false);
  a(
    assertStrictEquals,
    layoutFinal.compilePayload.bundleOffset,
    layoutStart.compilePayload.bundleOffset + embedPayloadWritten,
  );
  a(
    assertStrictEquals,
    layoutFinal.compilePayload.metadataOffset,
    layoutStart.compilePayload.metadataOffset + embedPayloadWritten,
  );
  console.log(ok ? "Binary OK 📦✅" : "❌");
  binary.close();
  // Do next binary...
}
```

The line `console.log(e)` displays "AssertionError". I've tried

```
console.log(e);
console.log(e.toString());
console.log(e.message);
console.log(e.message.toString());
console.log(JSON.stringify(e)); // {"name":"AssertionError"}
console.log(JSON.stringify(e.message)); // ""
```

without any luck. How can I display the AssertionError message? Not sure if this is a bug or I'm missing something. Thanks

**Comment by nayeemrmn** [comment]
You have to supply the assertion error messages yourself:
```ts
a(assert, layoutFinal.compilePayload !== false, "Expected layoutFinal.compilePayload !== false");
a(
  assertStrictEquals,
  layoutFinal.compilePayload.metadataOffset,
  layoutStart.compilePayload.metadataOffset + embedPayloadWritten,
  "Expected ..."
);
```

**Comment by heyheyhello** [comment]
No it's optional.

![image](https://user-images.githubusercontent.com/44614862/110850299-7bc85880-8264-11eb-9717-2762ea559b71.png)

**Comment by nayeemrmn** [comment]
`assertStrictEquals` indeed does... but I can't reproduce the issue:
```ts
import * as asserts from "https://deno.land/std@0.87.0/testing/asserts.ts";
try {
  asserts.assertStrictEquals(1, 2);
} catch (e) {
  console.log(e);
}
```
```
AssertionError: Values are not strictly equal:


    [Diff] Actual / Expected


-   1
+   2

    at Module.assertStrictEquals (https://deno.land/std@0.87.0/testing/asserts.ts:363:1)
    at file:///home/nayeem/projects/deno/temp.ts:3:1
```

**Comment by heyheyhello** [comment]
The `console.log(e)` wasn't displaying anything because there was no error 3/4 asserts 🙃🙃🙃
Thank you!

I made it more clear with this
```ts
const a = (
    assertion: typeof assert | typeof assertStrictEquals,
    ...args: unknown[]
  ) => {
    try {
      // @ts-ignore Shhh
      assertion(...args);
      console.log(assertion.name, "PASSED");
    } catch (e) {
      ok = false;
      console.log(assertion.name, "FAILED");
      console.log(e);
    }
  };
```

```
assert PASSED
assert FAILED
AssertionError
    at assert (https://deno.land/std@0.89.0/testing/asserts.ts:175:11)
    at a (file:///home/today/_/work/localstar/server/scripts/embed.ts:259:7)
    at file:///home/today/_/work/localstar/server/scripts/embed.ts:269:3
assertStrictEquals PASSED
assertStrictEquals PASSED
```
