### ISSUE TITLE
[autocannon] Uncaught (in promise) BrokenPipe: Broken pipe

### ISSUE THREAD

**Issue by ynwd** [denoland/deno_std#833]
Error:
```
error: Uncaught (in promise) BrokenPipe: Broken pipe (os error 32) 
      throw new ErrorClass(res.err.message);
            ^
    at unwrapResponse (deno:runtime/js/10_dispatch_minimal.js:60:13)
    at sendAsync (deno:runtime/js/10_dispatch_minimal.js:99:12)
    at async write (deno:runtime/js/12_io.js:118:20)
    at async Object.writeAll (deno:runtime/js/13_buffer.js:224:19)
    at async BufWriter.flush (bufio.ts:468:7)
    at async writeResponse (_io.ts:288:3)
    at async ServerRequest.respond (server.ts:89:7)
```

Step to reproduce:
- Install fastro:
  ```
  deno install -A https://deno.land/x/fastro@v0.30.36/cli/fastro.ts
  ```
- Init folder:
  ```
  mkdir webapp && cd webapp && fastro init
  ```
- Run fastro:
  ```
  deno run -A main.ts
  ```
- Install autocannon: https://www.npmjs.com/package/autocannon
- Run autocannon:
  ```
  autocannon -c 100 -d 40 -p 10 localhost:8080/hello
  ```
  
  (this command line is taken from https://github.com/fastify/benchmarks)

**Comment by FujiHaruka** [comment]
@bnoordhuis 

It seems that this is already fixed in the current version (`0.127.0`) of the std library.

**Common conditions**

```
$ deno --version
deno 1.19.1 (release, x86_64-apple-darwin)
v8 9.9.115.7
typescript 4.5.2
```

**With version `0.86.0`**

main.ts

```ts
import { serve } from "https://deno.land/std@0.86.0/http/server.ts";

const server = serve({ hostname: "0.0.0.0", port: 8080 });

for await (const request of server) {
  const res = {
    body: "Hello World",
    headers: new Headers(),
  };
  res.headers.set("Date", new Date().toUTCString());
  res.headers.set("Connection", "keep-alive");
  request.respond(res)
}

```

I tested the server by launching server with `deno -A main.ts` and running the following command.

```
$ npx autocannon -c 100 -d 10 -p 10 localhost:8080/hello
```

Then, the server process exited with the following error.

```
error: Uncaught (in promise) BrokenPipe: Broken pipe (os error 32)
      await Deno.writeAll(
      ^
    at async write (deno:ext/net/01_net.js:28:12)
    at async Object.writeAll (deno:runtime/js/13_buffer.js:241:19)
    at async BufWriter.flush (https://deno.land/std@0.86.0/io/bufio.ts:468:7)
    at async writeResponse (https://deno.land/std@0.86.0/http/_io.ts:288:3)
    at async ServerRequest.respond (https://deno.land/std@0.86.0/http/server.ts:89:7)
```

**With version `0.127.0`**

main.ts

```ts
import { serve } from "https://deno.land/std@0.127.0/http/server.ts";

serve(() => {
  const headers = new Headers();
  headers.set("Date", new Date().toUTCString());
  headers.set("Connection", "keep-alive");
  return new Response("Hello World", {
    headers,
  });
}, {
  hostname: "0.0.0.0",
  port: 8080,
});
```

I tested the server by the same commands as above, and confirmed that the server process did not exit with errors.

**Comment by kt3k** [comment]
@FujiHaruka Thank you for checking this! I also confirmed this doesn't happen anymore with the latest `http/server`. Let's close this issue.

**Comment by kt3k** [comment]
BTW we've completely replaced the http server implementation at https://github.com/denoland/deno_std/pull/1128. I guess that made the difference
