### ISSUE TITLE
Property 'boundary' is used before its initialization.

### ISSUE THREAD

**Issue by pierreavn** [denoland/deno_std#856]
Hi, I'm trying to use a library (`alosaur`) using `deno_std`, but I have the following issue when I'm trying to run the app:
```bash
error: TS2729 [ERROR]: Property 'boundary' is used before its initialization.
  readonly newLineDashBoundary = encoder.encode(`\r\n--${this.boundary}`);
                                                              ~~~~~~~~
    at https://deno.land/std@0.84.0/mime/multipart.ts:263:63

    'boundary' is declared here.
      constructor(reader: Deno.Reader, private boundary: string) {
                                       ~~~~~~~~~~~~~~~~~~~~~~~~
        at https://deno.land/std@0.84.0/mime/multipart.ts:268:36

TS2729 [ERROR]: Property 'boundary' is used before its initialization.
  readonly dashBoundaryDash = encoder.encode(`--${this.boundary}--`);
                                                       ~~~~~~~~
    at https://deno.land/std@0.84.0/mime/multipart.ts:264:56

    'boundary' is declared here.
      constructor(reader: Deno.Reader, private boundary: string) {
                                       ~~~~~~~~~~~~~~~~~~~~~~~~
        at https://deno.land/std@0.84.0/mime/multipart.ts:268:36

TS2729 [ERROR]: Property 'boundary' is used before its initialization.
  readonly dashBoundary = encoder.encode(`--${this.boundary}`);
                                                   ~~~~~~~~
    at https://deno.land/std@0.84.0/mime/multipart.ts:265:52

    'boundary' is declared here.
      constructor(reader: Deno.Reader, private boundary: string) {
                                       ~~~~~~~~~~~~~~~~~~~~~~~~
        at https://deno.land/std@0.84.0/mime/multipart.ts:268:36

Found 3 errors.
```
You can reproduce this with the alosaur example here:
https://github.com/alosaur/alosaur#simple-example
Do you have any clue about this issue?
Thank you in advance for your work!

**Comment by lucacasonato** [comment]
This issue is resolved in newer versions of `deno_std`. Please update deno_std to the latest version in alosaur or other dependencies. You can see which dependency is pulling in `std@0.84.0` with `deno info`.

**Comment by pierreavn** [comment]
Indeed, got it, thank your for your help!
