### ISSUE TITLE
Make `encoding/yaml.ts` type-compatible with Deno Deploy

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#907]
Currently yaml can't be used in Deploy because of the following errors:

```shellsession
$ deployctl run test.ts 
Check file:///Users/kt3k/tmp/deploy-test/$deno$eval.ts
error: TS2694 [ERROR]: Namespace 'Deno' has no exported member 'Reader'.
  async readFrom(r: Deno.Reader): Promise<number> {
                         ~~~~~~
    at https://deno.land/std@0.95.0/io/buffer.ts:196:26

TS2694 [ERROR]: Namespace 'Deno' has no exported member 'ReaderSync'.
  readFromSync(r: Deno.ReaderSync): number {
                       ~~~~~~~~~~
    at https://deno.land/std@0.95.0/io/buffer.ts:226:24

Found 2 errors.
error: Process exited with code 1
```

**Comment by wperron** [comment]
Maybe we could add `Reader` and `Writer` types to Deploy? :thinking:

**Comment by lucacasonato** [comment]
Plan to fix this in https://github.com/denoland/deno/issues/9795
