### ISSUE TITLE
std/io/buffer.ts: A method cannot be named with a private identifier

### ISSUE THREAD

**Issue by talentlessguy** [denoland/deno_std#961]
Hello, after bumping some of the libraries many of my libraries broke with this weird error. Not sure what's causing it but looks like an std li fault

```
Check file:///home/runner/work/forwarded/forwarded/$deno$test.ts
error: TS18022 [ERROR]: A method cannot be named with a private identifier.
  #tryGrowByReslice(n: number) {
  ~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.98.0/io/buffer.ts:85:3

TS18022 [ERROR]: A method cannot be named with a private identifier.
  #reslice(len: number) {
  ~~~~~~~~
    at https://deno.land/std@0.98.0/io/buffer.ts:94:3

TS18022 [ERROR]: A method cannot be named with a private identifier.
  #grow(n: number) {
  ~~~~~
    at https://deno.land/std@0.98.0/io/buffer.ts:141:3

Found 3 errors.
Error: Process completed with exit code 1.
```

example repo: https://github.com/deno-libs/forwarded

**Comment by talentlessguy** [comment]
closing, this only happens in Deno >1.11, the solution is to upgrade to latest Deno
