### ISSUE TITLE
std@0.98.0/log TypeScript errors

### ISSUE THREAD

**Issue by n-kort** [denoland/deno_std#974]
`deno --version` = `1.8.0`

The following example from the readme throws some TypeScript errors:

```typescript
import * as log from "https://deno.land/std@0.98.0/log/mod.ts";

log.debug("Hello world");
log.info(123456);
log.warning(true);
log.error({ foo: "bar", fizz: "bazz" });
log.critical("500 Internal server error");

await log.setup({
  handlers: {
    console: new log.handlers.ConsoleHandler("DEBUG"),

    file: new log.handlers.FileHandler("WARNING", {
      filename: "./log.txt",
      formatter: "{levelName} {msg}",
    }),
  },

  loggers: {
    default: {
      level: "DEBUG",
      handlers: ["console", "file"],
    },

    tasks: {
      level: "ERROR",
      handlers: ["console"],
    },
  },
});

let logger;

logger = log.getLogger();
logger.debug("fizz"); // logs to `console`, because `file` handler requires "WARNING" level.
logger.warning(41256); // logs to both `console` and `file` handlers.

logger = log.getLogger("tasks");
logger.debug("fizz"); // won't get output because this logger has "ERROR" level.
logger.error({ productType: "book", value: "126.11" }); // log to `console`.

const unknownLogger = log.getLogger("mystery");
unknownLogger.info("foobar"); // no-op
```

Running `deno run --allow-write mod.ts` gives shows:

```
Check file:///bla/bla/mod.ts
error: TS18022 [ERROR]: A method cannot be named with a private identifier.
  #tryGrowByReslice(n: number) {
  ~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.98.0/io/buffer.ts:85:3

TS18022 [ERROR]: A method cannot be named with a private identifier.
  #reslice(len: number) {
  ~~~~~~~~
    at https://deno.land/std@0.98.0/io/buffer.ts:94:3

TS18022 [ERROR]: A method cannot be named with a private identifier.
  #grow(n: number) {
  ~~~~~
    at https://deno.land/std@0.98.0/io/buffer.ts:141:3

TS18022 [ERROR]: A method cannot be named with a private identifier.
  #unloadCallback() {
  ~~~~~~~~~~~~~~~
    at https://deno.land/std@0.98.0/log/handlers.ts:105:3

Found 4 errors.
```

Version 0.97.0 works as expected.

**Comment by lucacasonato** [comment]
Use Deno 1.11. Run `deno upgrade` to update.
