### ISSUE TITLE
Calling assertThrows on class method makes "this" undefined

### ISSUE THREAD

**Issue by mmykhaylov** [denoland/deno_std#979]
**Describe the bug** 
When testing a class and expecting one of the methods to throw, assertThrows makes the value of "this" undefined. This makes my test fail, as the thrown error (TypeError, can't read property of undefined) is not the expected error (RangeError, Linked list empty)

**To Reproduce**

***index.ts***
```ts
class SinglyLinkedNode<T> {
  val: T;
  next: SinglyLinkedNode<T> | null;

  constructor(val: T) {
    this.val = val;
    this.next = null;
  }
}

export class SinglyLinkedList<T> {
  public length = 0;
  public head: SinglyLinkedNode<T> | null = null;
  public tail: SinglyLinkedNode<T> | null = null;

  constructor() { }

  push(val: T): SinglyLinkedNode<T> {
    const node = new SinglyLinkedNode<T>(val);
    // If not tail then list is empty, setting head
    // Otherwise, add node to tail's next
    if (!this.tail) {
      this.head = node;
    } else {
      this.tail.next = node;
    }
    // and update tail to be the new node
    this.tail = node;
    this.length++;
    return node;
  }
  pop() {
    console.log(this)
    if (!this.head) {
      throw new RangeError('Linked list empty');
    }
    let currNode = this.head;
    let prevNode: SinglyLinkedNode<T> | null = null;
    while (currNode.next) {
      prevNode = currNode;
      currNode = currNode.next;
    }
    if (prevNode) {
      prevNode.next = null;
    }
    this.head = prevNode ? this.head : null;
    this.tail = prevNode;
    this.length--;
    return currNode;
  }
}
```

***index.test.ts***
```ts
import { assertEquals, assertThrows } from 'https://deno.land/std@0.99.0/testing/asserts.ts';
import { SinglyLinkedList } from './index.ts';

Deno.test('Popping empty list causes range error', () => {
  const list = new SinglyLinkedList<string>();
  assertThrows(list.pop, Error, 'Linked list empty', "Popping shouldn't work on empty lists");
});
```

**Terminal output when running the test**
```
running 1 test from FILENAME
test Popping empty list causes error ...undefined // undefined is the console.log(this) from pop method
 FAILED (8ms)

failures:

Popping empty list causes error
AssertionError: Expected error to be instance of "RangeError", but was "TypeError": Popping shouldn't work on empty lists
    at assertThrows (https://deno.land/std@0.99.0/testing/asserts.ts:576:13)
    at FILENAME
    at asyncOpSanitizer (deno:runtime/js/40_testing.js:21:15)
    at resourceSanitizer (deno:runtime/js/40_testing.js:58:13)
    at exitSanitizer (deno:runtime/js/40_testing.js:85:15)
    at runTest (deno:runtime/js/40_testing.js:199:13)
    at Object.runTests (deno:runtime/js/40_testing.js:244:13)
    at FILENAME

failures:

        Popping empty list causes error
```

**Expected behavior**
***Terminal output when running the test***
```
running 1 test from FILENAME
test Popping empty list causes error ...SinglyLinkedList {
  length: 0,
  head: null,
  tail: null
}
 ok (9ms)
```

**Desktop (please complete the following information):**

- OS: macOS 11.4 Big
- Version

```
deno 1.11.1 (release, x86_64-apple-darwin)
v8 9.1.269.35
typescript 4.3.2
```

**Comment by caspervonb** [comment]
```ts
assertThrows(function() {
  list.pop()
}, Error, 'Linked list empty', "Popping shouldn't work on empty lists");
```

**Comment by mmykhaylov** [comment]
Thank you, that solved my problem. Closing

P.S: could you link some resource that explains this bit?

**Comment by caspervonb** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this#as_an_object_method
